### PR TITLE
Fix misc. typos

### PR DESCRIPTION
**Pull request by luzpaz**
`codespell -q 3 -S *.ts,./libs,./sample-projects -L searchin`

### CODE REVIEW

**Comment by gedakc** [comment]
Thank you @luzpaz for your interest in Manuskript and your efforts to make it better.

This PR identifies a number of spelling mistakes to fix which is a good thing.

However some of the spelling changes involve automatically generated content, and one spelling change affects executable code.  As such I have some suggestions for this Pull Request.

1.  Because the `CHANGELOG.md` file is automatically generated from the github project (see bottom of [`CHANGELOG.md`](https://github.com/olivierkes/manuskript/blob/develop/CHANGELOG.md)), I do not know the implications of making manual changes.  Will these manual changes be overwritten on the next automatic generation?  Is it better to try to fix the spelling mistakes in the title of the original Issue or Pull Request?

    Would you please test automatic generation, or else remove all the changes to `CHANGELOG.md` in this PR.  

2. This PR identifies itself as fixing spelling mistakes, but also changes executable code (see misspelled "stlye" in [manuskript/ui/highlighters/markdownHighlighter.py#L679](https://github.com/olivierkes/manuskript/blob/d7203ddacf3fd38517bd107d2b7cfc89ca21a3c8/manuskript/ui/highlighters/markdownHighlighter.py#L679).

    Please place this executable code change in a separate PR.  Please also test to see what this change fixes and include this in the PR description / commit message.

**Comment by luzpaz** [comment]
I will follow-up when I have another moment. Thanks.

**Comment by worstje** [comment]
@luzpaz What is the status on this?

**Comment by luzpaz** [comment]
forgot about this. Will look in to it

**Comment by luzpaz** [comment]
@worstje  
Both 4ddab3d & fe5777b are the reverted code requested by @gedakc  
b714864 are a few more typos I just found, that need review

**Comment by worstje** [comment]
Can you rebase your entire set of changes against the current develop branch?

I am not entirely sure happened here, but I think you left your Feb 10 changes in (8830ea1), pulled in new more recent changes from develop, and then wrote these new patches against your old patch, leading to the commits where you 'revert'.

Ideally your PR only has the 'Misc. typos' and 'Add a few more typos' fixes. (And even those can be squashed together into a single commit.

**Comment by luzpaz** [comment]
squashed and ready to go

**Comment by worstje** [comment]
I'd amend the commit message a bit still because some of that description doesn't make sense anymore now that you've tidied it up. Other than that, it looks good! 👍

**Comment by luzpaz** [comment]
Yea, makes sense. Amended.

**Comment by gedakc** [comment]
@luzpaz are you able to make the suggested "save" -> "saved" changes in the next day or so?

If not then I will plan to merge this as-is and make the change afterwards.

**Comment by luzpaz** [comment]
@gedakc i don't follow? was there a suggestion that I missed ?

**Comment by gedakc** [comment]
This looks like my bad.  I must have been reviewing an older commit in my comments above.

When pulled your changes into my local repo, I can clearly see that you did change "save" to "saved" in both the files:
- manuskript/ui/settings_ui.py
- manuskript/ui/settings_ui.ui

I will plan to merge this PR for inclusion in the next release of Manuskript.

Thank you for your help.

**Comment by luzpaz** [comment]
@gedakc you're absolutely right, I did miss a fix. Apologies. Added in #648

**Comment by gedakc** [comment]
@luzpaz no worries.  I just remembered that yesterday I had pulled down your other PR with the typo fixes and then had made the "save" -> "saved" change locally.  But with all the other work I did yesterday I forgot.

I'm glad you double-checked.  I will merge this with the **develop** branch after the current [Travis CI](https://travis-ci.org/olivierkes/) processes complete.

**Pull request merged**
