### PR TITLE
Updated pt_PT translations

### PR DESCRIPTION
**Pull request by pmraps**

### CODE REVIEW

**Comment by gedakc** [comment]
Thank you for this update.  It looks like we are half-way to getting the change based on the **develop** branch for @olivierkes repository, but it is not based on the **develop** branch from your local clone.

The code change should be based against the **develop** branch.  By this I mean that the file changes need to be applied to a local branch on your computer that is based on @olivierkes **develop** branch.

**Comment by gedakc** [comment]
Following is a picture that graphically shows how the code change is based on the **master** branch, and not the **develop** branch.

pr-not-based-on-develop-branch

**Comment by pmraps** [comment]
Like I said, github ignorant. :(.
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 13/11/18, 17:39 Curtis Gedak <notifications@github.com> wrote:
Following is a picture that graphically shows how the code change is based on the master branch, and not the develop branch.


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/olivierkes/manuskript","title":"olivierkes/manuskript","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/olivierkes/manuskript"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gedakc in #410: Following is a picture that graphically shows how the code change is based on the **master** branch, and not the **develop** branch.\r\n\r\npr-not-based-on-develop-branch\r\n"}],"action":{"name":"View Pull Request","url":"https://github.com/olivierkes/manuskript/pull/410#issuecomment-438366023"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/olivierkes/manuskript/pull/410#issuecomment-438366023",
"url": "https://github.com/olivierkes/manuskript/pull/410#issuecomment-438366023",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [olivierkes/manuskript] Updated pt_PT translations (#410)",
"sections": [
{
"text": "",
"activityTitle": "**Curtis Gedak**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@gedakc",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"olivierkes/manuskript\",\n\"issueId\": 410,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"olivierkes/manuskript\",\n\"pullRequestId\": 410\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/olivierkes/manuskript/pull/410#issuecomment-438366023"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 409725033\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by gedakc** [comment]
No worries.  I will try to manually include the language translations updates when I prepare the next official release.

**Comment by gedakc** [comment]
The file from issue #408 will be manually included in the **0.8.0** release.

**Pull request closed without merging**
