### PR TITLE
Add snap build and package

### PR DESCRIPTION
**Pull request by tomwardill**
Hi,

Referencing https://github.com/olivierkes/manuskript/issues/71 I have created a snap build for the manuskript project. This should work on any platform supported by snapd.

This can be built by installing [snapcraft](https://docs.snapcraft.io/snapcraft-overview/8940) and running `make snap`, or `snapcraft` in the project directory.

I haven't registered the name in the store as I didn't want to appear to be namesquatting or similar, though I'm happy to do that, fill in the metadata and transfer it to you if you'd prefer.

This can be released to the store following the [release instructions](https://docs.snapcraft.io/releasing-your-app/6795)

I'm happy to answer any questions and help if I can.

### CODE REVIEW

**Comment by gedakc** [comment]
Thank you @tomwardill for creating a snap package for Manuskript.

FYI:  Due to other plans it will be next week before I have a chance to review this PR in earnest.

**Comment by tomwardill** [comment]
Thanks for the timely response and the consideration @gedakc . I don't anticipate there being much code drift in this so it should stay in a reviewable state.
I'm using the snap for writing some papers for work, so will have chance to test it out fully.

**Comment by gedakc** [comment]
Hi @tomwardill,

First, thank you for developing a method to create snap packages.  I like that you have built in automation for creating the package, such as adding to the makefile.  This should make building snap packages easier in the future.

I also appreciate you consideration regarding how the Manuskript name and access owner / rights should be set up on the snap store. 

Before I comment further I would like to point out that I am not familiar with snap and snapcraft so if anything I say seems strange, then please do correct me.

Following are some suggestions and questions.

1.  Is it possible to place the `snap` directory and files in the `package` directory with the other scripts that create packages?

2.  Can you automate placing the actual version number (contained in `manuskript/version.py`) into the `snapcraft.xml` file?  
   For example see `package/create_deb.sh`.

3.  Could you change the snap meta data to be consistent with current Manuskript "branding"?  
   For example the `summary:` section in the `snapcraft.xml` file introduces a new description that is not entirely accurate because Manuskript can be used by writers who do not plan extensively before writing.  Currently the summary we use is "_Manuskript is an open-source tool for writers._"

4. Can you clean up the commits the PR?  
   For example the "Add icon" commit currently adds an `icon:` line to `snap/snapcraft.xml`, but the `snapcraft.xml` file does not get added until a later "Add snapcraft.xml" commit.

5. Would you like to volunteer to maintain the snap packages going forward?  
   This can help decide who would need access to publish new snap packages.

Note that I haven't tried building or installing the snap package yet.  So far my comments are from a code review only.

Regards,  
Curtis

**Comment by tomwardill** [comment]
Hi,
Sorry for the slow reply on this, trying to move house takes more time than I expected.

1. Snapcraft (and build.snapcraft.io) prefer to have the `snapcraft.yaml` at either /snapcraft.yaml, /.snapcraft.yaml or /snap/snapcraft.yaml. I can't seem to make the snapcraft command respect any other location, and moving it elsewhere would remove the possibility of using build.snapcraft.io to create automated builds. I'm happy to have another look, or move it to one of the other options, if it's a requirement though
2. Done, sorry, should've checked this to start with.
3. Changed the summary.
4. Rebased and squashed relevant commits together.
5. Sure, I can do that. I only use manuskript rarely, but happy to maintain the package onwards.

Thanks,
Tom

**Comment by gedakc** [comment]
Hi @tomwardill,

No worries on your response time.  Manuskript is built using volunteer efforts.  We help only when we can.  :-)

1.  Thanks for the explanation on the `snapcraft.xml` location.  Of the options mentioned the `snap` subdirectory is my preference.

2. Auto-version update.  Cool.

3. Summary change acknowledged.

4. Thanks for the rebase and squash.  The current commits are much cleaner and easier to follow.

5. A big thank you for offering to maintain and support the snap package for Manuskript.  Please feel free to set up the account(s) needed for snaps.  Later when things are working we can look into adding access for myself @gedakc and @olivierkes if he is interested.

Two more items:

6. I noticed the `snapcraft.xml` file indicates `grade: stable`.  If this is meant to imply that manuskript is at a stable point in development then that would be incorrect.  Perhaps use **Beta**?  
   On the [GitHub releases](https://github.com/olivierkes/manuskript/releases) page we indicate **Pre-release**.  On the [Manuskript Download](https://www.theologeek.ch/manuskript/download/) page we have a warning posted.  Further we have had isolated reports of file corruption on Windows with the most recent being issue #502.

7. I tried to use snapcraft in my Ubuntu 14.04 Virtual Machine but things have not gone well.  The first install attempt broke the VM such that the mouse no longer worked.  After rebuilding the entire VM and installing snapcraft it appears that snaps cannot be built with Ubuntu 14.04.  The first issue I encounter is with the makefile:

       $ make snap
       make: `snap' is up to date.

   The second issue I encounter is that multipass does not appear to be supported on Ubuntu 14.04:

       $ snapcraft snap
       You need multipass installed to build snaps (https://github.com/CanonicalLtd/multipass).
       Would you like to install it now? [y/N]: y
       Failed to install or refresh a snap: 'multipass' does not exist or is not available on the desired channel 'latest/beta'. Use `snap info multipass` to get a list of channels the snap is available on.
       $ snap info multipass
       error: no snap found for "multipass"

   What are your suggestions to address these snap build issues?

Cheers,  
Curtis

**Comment by tomwardill** [comment]
Hi,

I'm still busy with moving house (my life is mostly packaging of a physical kind and involves a lot of cardboard atm), but I've not abandoned this.

I'll register the names and accounts asap so builds can start flowing when they're ready.

The `grade` in a snapcraft.yaml is optional and imposes some limitations on releases if it's not 'stable'. The documentation is here: https://docs.snapcraft.io/snapcraft-yaml-reference/4276
It's worth noting that this isn't the best way to model the release cycle of an application, as that is better done through the release channels and risk levels (stable, candidate, beta, edge). Marking the `grade` as stable just allows releasing to stable and candidate, but doesn't imply that it has to be.

I've not had time to investigate your build problems, but for reference I'm building on 16.04 and 18.04, I'll have a look at trying to work out what's going on for 14.04 when I get chance.

Thanks,
Tom

**Comment by gedakc** [comment]
Hi Tom,

'Hope your move is going / has gone well.

I was able to successfully run the `snapcraft` command on an Ubuntu 18.04 Virtual Machine.

However I still encounter a problem with `make snap`.  It seems that `snap` might be a reserved word for makefiles of something.

If I rename the target in the makefile from `snap` to `snappkg` then `make snappkg` works.

Would you please update this PR accordingly?

Thanks,  
Curtis

**Comment by gedakc** [comment]
Since we are planning a new Manuskript release and we would like to include this enhancement, I will rebase and commit this PR.  Following that I plan to make the above listed makefile target name change.

**Comment by tomwardill** [comment]
Hi!

Sorry, I've been really bad at keeping this updated.

I'll do the Makefile change this evening.
I have applied for the manuskript name on the snap store, but it has a conflict with an already registered name. I've applied for a name conflict resolution and am awaiting the results of that.

**Comment by gedakc** [comment]
Hi Tom,

Thanks for the update on the snap store progress.

I've already initiated the rebase and merge, so no need to update the makefile.  I will make the makefile target change.

Cheers,  
Curtis

**Comment by jshamg** [comment]
@tomwardill @gedakc can someone please set the environment variable "DISABLE_WAYLAND: 1" when building the snap and update it? It's a quick fix for all of us Wayland users not being able to run the snap... 
It just forces the snap to use X11. You guys can read about it in this thread: [here](https://forum.snapcraft.io/t/problem-launching-qt-snaps-in-wayland/7055) ... I would be very happy :)

Greetings from Germany,
Josh

**Pull request merged**
