### PR TITLE
fix translator

### PR DESCRIPTION
**Pull request by lingsamuel**

### CODE REVIEW

**Comment by gedakc** [comment]
Thank you @lingsamuel for this bug fix.

Good work finding the cause of translations not being loaded into the **Edit -> Settings** window.  :-)

In my testing this PR enabled the correct language translations to be viewed in the **Edit -> Settings** window.

With Manuskript we use the **develop** branch for all new bug fixes and enhancements.

Would you be able to base this PR on the **develop** branch?

Also would you be able to update the commit message with more details, and to link it with issue #411?

Descriptive commit messages and links between PRs and issues helps us with future trouble-shooting.

Thanks,
Curtis

**Comment by lingsamuel** [comment]
Oh sorry, this pr base on master is a mistake. I think you can set the `default branch` in https://github.com/olivierkes/manuskript/settings/branches to avoid this situation.

**Comment by gedakc** [comment]
Hi @lingsamuel,

>  I think you can set the default branch in https://github.com/olivierkes/manuskript/settings/branches to avoid this situation.

I think your idea is a good one to set the default branch for PRs to **develop**.  Unfortunately I do not have write access to this area of @olivierkes github account/repository.  Further I have received no response to emails requests to him to update weblate.  If you have a twitter account (I do not have one for personal reasons), then you might try contacting him at his https://twitter.com/olkesh twitter address.

Regards,
Curtis

**Comment by gedakc** [comment]
Thank you @lingsamuel for updating the commit message and rebasing on the **develop** branch.

From my testing I confirmed that this enhancement makes translations available in the **Edit -> Settings** window.

I will rebase and merge this PR with the **develop** branch.

**Comment by gedakc** [comment]
I recently received write access to weblate and have "pushed" these changes to weblate.

If you have time please check the `i18n/manuskript_zh_CN.ts` translation as I had to fix one conflict when merging.  The string in question had **`HTML`** near the end.

**Pull request merged**
