### PR TITLE
Add moving World Items

### PR DESCRIPTION
**Pull request by JackXVII**
Add internal drag&drop of World items #219.
If you drag several items, after drop they will have the same parent (the one in which the drop was made).

### CODE REVIEW

**Comment by gedakc** [comment]
Thank you @JackXVII for this PR to enhance manuskript.

@olivierkes will you have chance to review this PR?

If not then I can take a look at it in a day or so.

**Comment by olivierkes** [comment]
Thank you very much @JackXVII! Just read your code and it looks good to me. I'll test it in a few days. If you can do it do @gedakc it would be great :)

**Comment by gedakc** [comment]
FYI: I will begin reviewing this PR so that we don't end up duplicating work.

**Comment by gedakc** [comment]
Thank you again @JackXVII  for creating a patch to enable moving of world items.

While testing I encountered a problem.

# Problem

When moving a World item that contains sub-items and placing it under another World item, the sub-items disappear (are silently deleted).

# Steps to Reproduce

Start with a project that contains no World Items.

1. Create "World trait 1"
2. Create "World trait 2"
3. Under "World trait 1" create "World trait 3"

    world-before

    [Optional] If setting **Save to one single file** is disabled then `world.opml` looks like the following:
    ```
    <?xml version='1.0' encoding='UTF-8'?>
    <opml version="1.0">
      <body>
        <outline name="World trait 1" ID="0">
          <outline name="World trait 3" ID="2"/>
        </outline>
        <outline name="World trait 2" ID="1"/>
      </body>
    </opml>
    ```
4. Select "World trait 1" and drag and drop it on "World trait 2".
5. Notice that "World trait 2" disappears (is silently deleted).

    world-after

    [Optional] If setting **Save to one single file** is disabled then one can look at the world.opml file and confirm that "World trait 3" has indeed been deleted.
    ```
    <?xml version='1.0' encoding='UTF-8'?>
    <opml version="1.0">
      <body>
        <outline name="World trait 2" ID="1">
          <outline name="World trait 1" ID="0"/>
        </outline>
      </body>
    </opml>
    ```

If you need any more information to re-create the problem then please don't hesitate to ask.

**Comment by JackXVII** [comment]
Fixed. Thank you for testing @gedakc .

**Comment by gedakc** [comment]
Thank you @JackXVII for promptly creating a patch to fix the issue with World sub-items disappearing on move.  Sub-items now appear to move correctly along with the parent item.  :-)

While testing I encountered another problem.

# Problem 2

When moving a World item that contains sub-items and placing it just above the topmost World item, the move is not performed.  However an interesting side effect is that the sub-item is no longer displayed, but can be displayed by double-clicking the World item with the sub-item.

# Steps to Reproduce

Start with a project that contains no World Items.

1. Create "World trait 1"
2. Create "World trait 2"
3. Under "World trait **2**" create "World trait 3"

    world-1

    If setting **Save to one single file** is disabled then `world.opml` looks like the following:
    ```<?xml version='1.0' encoding='UTF-8'?>
    <opml version="1.0">
      <body>
        <outline name="World trait 1" ID="0"/>
        <outline name="World trait 2" ID="1">
          <outline name="World trait 3" ID="2"/>
        </outline>
      </body>
    </opml>
    ```
4. Select "World trait 2" and drag and drop it immediately above "World trait 1".  On my screen this is just before a symbol with a circle and cross is displayed, and is when a line is displayed just above "World trait 1".

5. Notice that "World trait 2" is not moved, but strangely "World trait 3" is no longer displayed.

    world-2

    *Note that "World trait 3" was not deleted and can be displayed by double-clicking on "World trait 2" and it will show up the same as before the move was attempted.*

    If setting **Save to one single file** is disabled then one can look at the `world.opml` file and confirm that is the same as the original.
    ```
    <?xml version='1.0' encoding='UTF-8'?>
    <opml version="1.0">
      <body>
        <outline name="World trait 1" ID="0"/>
        <outline name="World trait 2" ID="1">
          <outline name="World trait 3" ID="2"/>
        </outline>
      </body>
    </opml>
    ```

# Notes

The failure to perform the move can be worked around by instead dragging "World trait 1" below (not under) "World trait 2".

world-3

If setting **Save to one single file** is disabled then one can look at the `world.opml` file and confirm this move was performed correctly.  Further the "World trait 3" sub-item is still displayed.
```
<?xml version='1.0' encoding='UTF-8'?>
<opml version="1.0">
  <body>
    <outline name="World trait 2" ID="1">
      <outline name="World trait 3" ID="2"/>
    </outline>
    <outline name="World trait 1" ID="0"/>
  </body>
</opml>
```
 
If you need any more information to re-create the problem then please don't hesitate to ask.

**Comment by JackXVII** [comment]
I fixed the moving, but I can not fix that interesting side effect. I will try to fix it, but I do not know if I will succeed. In any case, many thanks to @gedakc for testing!

**Comment by gedakc** [comment]
Thank you @JackXVII for enhancing Manuskript so that World items can be moved.

All my tests worked as expected.  I'll bet that many users will be happier with the new functionality you added.  :-)

**Comment by gedakc** [comment]
Hi @JackXVII,

With your recent familiarity with World items, would you be able to take a look at [Issue 306 - Deleting multiple World items leaves/creates two empty items](https://github.com/olivierkes/manuskript/issues/306)?

Thanks,
Curtis

**Comment by olivierkes** [comment]
Thank you very much, both of you!! 

I couldn't find time yet to test it all, sorry, but I'm fully confident. This is an issue that was requested multiple time, so thanks. 

One question: have you tried dropping one parent item on one of it's children items? That was one issue I had to solved in drag n drop with text items.

**Comment by gedakc** [comment]
> One question: have you tried dropping one parent item on one of it's children items? That was one issue I had to solved in drag n drop with text items.

Great test idea.

I just tried it with the current **develop** branch and the UI correctly prevents dropping a parent item on one of it's children.  Further it displays a circle with a line through it to indicate the action is invalid.

**Comment by gedakc** [comment]
After looking at some earlier PRs I noticed that we have not been applying labels or milestones.  Hence I have removed the labels and milestones from this PR.

**Comment by olivierkes** [comment]
I think it was an error on my part not to add label to PR, it could be useful.

**Pull request merged**
