### PR TITLE
Resolves crashing in Outline mode (#355)

### PR DESCRIPTION
**Pull request by RiderExMachina**
Creates some catches to resolve crashing and seems to resolve the issue.

### CODE REVIEW

**Comment by gedakc** [comment]
Thanks @RiderExMachina for researching solutions to other issues.

Please make a separate branch and PR for each issue that you fix.  If all the code changes are related to a single issue then it is okay to have multiple rlelated commits in the same branch and PR.

This PR is difficult to review because it includes commits that address multiple issues which makes it harder to review and approve.

**Comment by RiderExMachina** [comment]
@gedakc 
I believe I understand what you're saying, but I believe I can explain.

The first commit (435e6b5) is fixing the crash from my earlier commit. In hindsight I should have created a branch based off of the master branch. I'll take that into consideration in the future.

The second and third commits all resolve the same issue (#355), I just made an error in a36c672 that I caught and committed through e698c96.

With that being said, how do you wish to proceed?

**Comment by gedakc** [comment]
> In hindsight I should have created a branch based off of the master branch.

Please base each new fix on the **develop** branch (not the **master** branch).


> The second and third commits all resolve the same issue (#355), I just made an error in a36c672 that I caught and committed through e698c96.

Please squash these two commits together because it makes no sense to have the second commit introduce an error and the third commit fix the error.

Each and every commit to the code base *should* work and allow manuskript to run.  In order for features like `git bisect` to work, all commits must function correctly.  Otherwise it makes it more difficult to determine when a regression problem is introduced.

'Hope that helps explain how to develop fixes and enhancements for manuskript.

**Comment by RiderExMachina** [comment]
> Please base each new fix on the develop branch (not the master branch).

Oh okay. Understood.

> Please squash these two commits together because it makes no sense to have the second commit introduce an error and the third commit fix the error.

It might be a while before I can do this, but I'll get to work on this ASAP.

**Comment by gedakc** [comment]
> It might be a while before I can do this, but I'll get to work on this ASAP.

No worries.  :-)

We do this work on our free time, so it takes as long as it takes to develop a good solution to a problem.  We strive for good to excellent, not perfect.

**Comment by RiderExMachina** [comment]
I believe the saying goes (or should go) "Perfection" is the enemy of "good enough".

**Comment by RiderExMachina** [comment]
@gedakc 

I spent most of the weekend looking up how to squash commits and haven't completely figured it out. What I think I want to do is something like `git rebase -i HEAD~2` and then put `squash` in front of one commit and `pick` in front of the second one? When I do that, I try to push the changes, but it seems like nothing has changed.

Is there something I'm doing incorrectly?

**Comment by gedakc** [comment]
@RiderExMachina what tests have you performed to determine if this patch is correctly handling the situation (e.g. not just avoiding the crash)?

**Comment by gedakc** [comment]
One tip might be to look at the code for the **Project tree** pane because shift-selecting multiple items seems to work.  At least no messages are displayed in the console when selecting multiple items.

**Comment by RiderExMachina** [comment]
@gedakc 

I'll see what I can do.

**Comment by RiderExMachina** [comment]
> What was your reason for changing from `QPersistentModelIndex` to `QModelIndex`?
> 
> What testing have you performed to see if the enhancement works?
> What testing have you performed to check for any regressions?

`QPersistentModelIndex` does not have a function called `internalPointer` but `QModelIndex` does. When I edited that line, and only that line, no errors were called, the program did not crash, and I was able to select multiple lines within the Outline View.

I suspect a programmer was either not planning on using `internalPointer` when the line was first written and forgot to change the line when they did, or they wrote the incorrect Qt call.

**Comment by gedakc** [comment]
The code being changed was originally changed as a result of [PR #308 - Use QPersistentModelIndex in textEditView](https://github.com/olivierkes/manuskript/pull/308), which was a response to [Issue #306 - Deleting multiple World items leaves/creates two empty items](https://github.com/olivierkes/manuskript/issues/306)

Have you tested deleting records to check for regressions in behaviour?

**Comment by RiderExMachina** [comment]
@gedakc I just attempted to reproduce the error as listed in #306 and I found no such issues with my patch.

**Comment by gedakc** [comment]
Thank you @RiderExMachina for finding a fix to issue #355.

A modified version of this PR has been merged into @olivierkes manuskript **develop** branch for inclusion in the next release of manuskript.

**Pull request closed without merging**
