### PR TITLE
Fixes: add character button does not set importance slider to default…

### PR DESCRIPTION
**Pull request by gedakc**
… value

See issue #102.

By default when a character is added to the character model, the
importance value is set to "0" (Minor).  However when the new
character is selected, the importance slider remains set to the value
of the previously selected character.

Steps to Reproduce:

1.  Click add character (plus sign) button.
2.  Select this "New character".
3.  Select "Basic infos" tab and change Name to "Bob".
4.  Move Importance slider all the way to the right (Main).
5.  Click add character (plus sign) button.
6.  Select this "New character".

    Note that the "New character" is shown in the character list pane
    under "Minor", but the Importance slider is still all the way to
    the right (Main).

This enhancement ensures that the corresponding character UI
importance slider is also set to the same default value.

This enhancement aligns the Character importance slider with the way the Plot importance slider works.  More specifically all new records are added at the lowest importance level.

### CODE REVIEW

**Comment by gedakc** [comment]
In the second commit listed above I fixed the numbering in the steps in the comment section of the commit.

**Comment by gedakc** [comment]
@olivierkes, while my second commit does appear to fix the issue, I think there might be a more appropriate solution.

With Model-View-Controller, I think that the model is supposed to not know anything about the Views.  The Model is only supposed to issue messages when something has changed.  Views, via the Controller, are supposed to subscribe to the messages if they need to do something based on a change.

In this situation, the character model **should not** tell the character importance slider (view) to update it's values.  _I think this is what I implemented with the second commit._

I will investigate further, but I am also open to suggestions.

**Comment by gedakc** [comment]
Hi @olivierkes.  I believe these new commits resolve three issues related to character importance, character tab disabling, and plot importance.  This new code should be in alignment with Model-View-Controller concepts.

Please review and either comment or commit.

**Comment by olivierkes** [comment]
Seems right to me. Good work, thanks!

**Pull request merged**
