### PR TITLE
Fix crash when regex is not valid (Fixes olivierkes#989)

### PR DESCRIPTION
**Pull request by jdanielp**
Wrap regex preparation in try-catch
Log when there is a problem preparing the regex

### CODE REVIEW

**Comment by TheJackiMonster** [comment]
Could you disable regex in the search UI if it's already the `import re` failing the use of it already? Otherwise we create UI which is misleading, I assume. Otherwise this looks as a good fix for now. Thank you.

**Comment by jdanielp** [comment]
I assume that  "import re" does not fail since it's standard library functionality. But, it would be easy enough to disable the checkbox. Problem is that the search functionality uses regex for all search, so if re doesn't import all search is dead in the water. Have I misunderstood you?

I was thinking we could change the text color in the lineedit when the regex is not valid. A better approach might be to put a fake search result, e.g. "bad regular expression" in the results with more feedback or add feedback to the status bar when the regex is not valid

**Comment by TheJackiMonster** [comment]
Mhmm... I also assumed `import re` would never fail at first. But it's inside the try & catch clause. So I wasn't sure. ^^'

Well... if it shouldn't fail, I think it should be imported outside the function like the other imports.

**Comment by jdanielp** [comment]
Yeah, I wrapped the whole function without discriminating. I'll fix that. Should we open a separate enhancement for indicating the regex is wrong or do you still want to handle it as part of this PR?

**Comment by jdanielp** [comment]
I went ahead and added the text color change when the regex fails to compile since it was straightforward.  Also will update when the search menu changes (checking, unchecking items).  I tested on my system (Windows 10) with a dark system theme.

**Comment by jdanielp** [comment]
Is there anything else needed on this PR?  I've fixed all the issues.

**Comment by TheJackiMonster** [comment]
I'll test it soon and merge it then.

**Pull request merged**
