### PR TITLE
I added a feature to add "detailed info" entries to multiple characters simultaneously via a dialog box.

### PR DESCRIPTION
**Pull request by tntscreed**
I tried to detail everything in the commit. Sorry if I messed something up, I don't have a lot of experience yet.

### CODE REVIEW

**Comment by TheJackiMonster** [comment]
> This will not affect anything else other than the "detailed info" rows. Every other change to a character's descriptions, motivations and such only affect the last selected one.

I see but I think this can lead to confusion by users. If there's now a selection for multiple characters at once it's not obvious which character will be affected by which changes without looking into the code, isn't it?

Maybe there's a solution to this. Have you looked into the PR #1113 which add character details templates? Maybe something like this could be added to the Qt code to deal with changing the detailed info of multiple characters at once?

**Comment by tntscreed** [comment]
@TheJackiMonster 

I see the problem, and I did start working on something for it. Only a few a fields should be mass-changeable, and the affected characters could be listed, though I'll have to change that UI element a bit. If I have to change a UI element, should I just change the py file, or do I make the ui file consistent with it to make the project more manageable?

I'm not sure how I could 'look into' another person's unapproved pull-request. Do I clone the fork into a separate local repo? Or do I just view the code on the website?

And sorry for the massive amount of questions, but should I close this pull-request until this is fixed?

**Comment by TheJackiMonster** [comment]
> If I have to change a UI element, should I just change the py file, or do I make the ui file consistent with it to make the project more manageable?

You probably want to use QtCreator or QtDesigner to adjust the UI file. Then you can run `make ui` in the repositories directory to generate the .py files from the .ui ones. So they are definitely consistent.

> I'm not sure how I could 'look into' another person's unapproved pull-request. Do I clone the fork into a separate local repo? Or do I just view the code on the website?

What I personally do is add a new remote to my local git repository with their fork and create a branch which sync's to their specific branch in their fork. Because git allows you to switch back and forth between branches as well as fetching from multiple different remotes. But you can also clone their fork into another local folder if that's easier to manage.

> And sorry for the massive amount of questions, but should I close this pull-request until this is fixed?

No worries. I wouldn't close this PR necessarily. The other PR I mentioned is editing the GTK code of the refactoring efforts. So it's pretty much independent of anything here. But I thought both efforts have a similar goal. So maybe it might be interesting to look into.

**Comment by tntscreed** [comment]
@TheJackiMonster 

Thank you for your answers. I'm not sure what is run by "make ui". There aren't any python files or executables by that name in the repository? I'm sorry, I'm very new. I just used pyuic on the specific ui file. But okay, so I should just leave the generated .py file untouched, then. I can do that.

I looked into their code, unfortunately I'm not too familiar with GTK. I saw that a button was added in the glade files, but I couldn't find it on the UI. The build also crashes with an index-out-of-bound error when adding more than 4 details one-by-one, for some reason.

But I do get what they were trying to do. It's similar in functionality, but not in implementation. Both of our ideas could be done without interfering with each other, though. I'll try to implement what I was originally trying to do first, if that's alright.

**Comment by TheShadowOfHassen** [comment]
I wrote the template for the Gtk because It is sapping to my writing time to every time I wanted to create a character and fill in their information "Hair Color, Eye Color Etc." I had to click a new value and put all the data in. Templates add more detail items to the more info, basically a template. The templates are stored in a dictionary with the name and then the template data as it's identified. I'd love to see this added to Qt so if your interested I can show you some UI images  so the design can be similar.

Also if you find a bug with the gtk port please open an Issue so either I or JackMonster can fix it. 

Thank you for contributing to this project!

**Comment by tntscreed** [comment]
@TheShadowOfHassen 
Hi! Yeah, I understand the concept, I just couldn't find the button on the UI, I did see the code for it. I would appreciate some images of the UI, yes. Thanks!

I found the bug in your fork when I was looking into the templates, not the main branch, I'm not sure if I should report it without any info. I have downloaded the gtk branch from this repo now, and I can't even get it to run for some reason. Yours ran, so I don't know how that happened. I tried to get it to work, but now I'm in the infamous dependency-hell, and I don't know if I should try to force it to work.

Are the python dependencies for the branch listed somewhere?

**Comment by TheShadowOfHassen** [comment]
I tried to add four data items on my fork and it worked fine. Could you give more information about that?

So there are some problems with the normal gtk branch. I couldn't get it to run. So I made the test.io file  in the main folder. That should be able to be copied and pasted into the other gtk branch.

So another problem we've come across is that if you download it from a zip the . msk files _won't work._ You'll need to go add your own .msk file to the test location and edit the file to load in test.io (To your file)



Here are the images of the Ui for the templates.  I think my side of the work is done with the pull request I just need @TheJackiMonster to approve of the pull.

Screenshot from 2023-03-05 15-36-30

Screenshot from 2023-03-05 15-36-42


Screenshot from 2023-03-05 15-36-11

**Comment by tntscreed** [comment]
@TheShadowOfHassen
Okay, I tried to get your gtk branch to work again, but I have absolutely no idea how to set up the dependencies on Windows. I've been trying for hours, I don't think it's happening.

However, this means I definitely never tried your gtk branch. All I could think of was that I accidentally cloned your develop branch, so I tried to replicate the bug on that. I couldn't. And it definitely wasn't my branch that I used when I got that error. It's possible the problem was an older project I was using to test things. Sorry about the confusion.

I still wish I could use your gtk branch to see the UI, though. I might try to get it to work on a VM with a linux distro. Could you maybe please send images of how it looks like during modification and creation of the templates?

**Comment by tntscreed** [comment]
@TheJackiMonster 
Hi! The bulk manager is now completely functional. When multiple characters are selected, all character tabs get hidden and a new one is created to manage everything. There is an add, delete and apply button. When apply is pressed, every added info gets added to all selected characters. The affected characters are also always shown in the tab.

I know the code is a bit messy, I accept any and all criticism, help or instruction on how to clean it up a bit. Or on any other part of the pull request. But I did test everything and I haven't found any bugs yet.

I also added functionality to delete all selected characters and - much more importantly - a dialog confirmation box before it happens, which I think should've even when only one character could be selected at a time.

**Comment by TheShadowOfHassen** [comment]
So I have a video. It doesn't show my mouse pointer but it shows the basics.

[Screencast from 03-11-2023 06_58_59 AM.webm](https://user-images.githubusercontent.com/94244235/224483314-a8ca9376-05b0-46e2-a641-857ac03d3dcd.webm)

**Comment by tntscreed** [comment]
@TheShadowOfHassen 

Yes, I did see how your code works when I finally managed to run the GTK branch on Ubuntu. It's definitely very useful, though I think a confirmation box would not hurt when overwriting an existing template. I think it's generally a problem with Manuskript that it's too easy to delete or overwrite huge amounts of work. If someone using it doesn't use source-control or make manual backups, it can very easily ruin their day.

The templates are a good idea, and I think I could add them over to my implementation on the QT branch. I think it would make a lot of sense, it would be pretty easy to add. I hope it's not too big of a problem if there's a little disparity between the branches. I'm still waiting on feedback from @TheJackiMonster on this pull-request, I don't know if I should start on it if the entire stuff has to be reworked.

**Comment by TheShadowOfHassen** [comment]
I'll work on an overwrite warning in another pull request. There are some other places that need conformations and I think it might be good to obfuscate it. The Gtk port is a long way from getting finished so I think I should have a bit of wiggle room of having it work 1000% in the first pull request.

I can't wait to see what your template manager looks like. Also I was figuring on just having them save as a .json file. That might be important if you can go ahead with saving (I can't in Gtk yet we're still figuring it out)

**Comment by TheJackiMonster** [comment]
@tntscreed Your changes look good so far. I've wanted to adjust some things but I couldn't push to your branch. However now Github automatically closed the PR... let me just reopen it. ^^'

**Comment by TheJackiMonster** [comment]
Nevermind, I don't think Github allows this. Hmm... I assume you can open a new PR for the templates.

Things I've adjusted already:
 - The strings for labels I've seen are now tracked for translation.
 - The translation files are updated with those strings.
 - The change for the extended selection was in the auto-generated Python-code only. So I've moved it into the .ui-file to be permanent.
- I've written a method to setup headers for person-info tables (their headers) consistently. It was weird before that the bulk manager extended the last column while the details view didn't.

Thanks for your contribution so far!

**Comment by tntscreed** [comment]
@TheJackiMonster 
Also, I've noticed that applying the details now does not work, because characterModel.py calls the new method, updatePersoInfoView, without the required argument.

**Comment by TheJackiMonster** [comment]
> Also, I've noticed that applying the details now does not work, because characterModel.py calls the new method, updatePersoInfoView, without the required argument.

Oh nice, really good catch! I totally thought this method had only been used inside of mainEditor.py because it was this specific.

**Pull request merged**
