### PR TITLE
Adding german translation

### PR DESCRIPTION
**Pull request by ScullyBlue**
I added a german translation for the tool. Its only the informal version (german "Du"), instead of the formal language (german "Sie"), but mostly I tried to use neutral, passive sentence, so it would be not so obviously.

I hope, its in the right format. It was my first time with Qt Linguist ... Often says by generating the ts-File "cannot be called without context" and the Files für english and spanish are much longer ...

### CODE REVIEW

**Comment by olivierkes** [comment]
Thanks a lot, I merged your translation to the `develop` branch.

**Comment by olivierkes** [comment]
Hey @ScullyBlue , we're about to release manuskript 0.5.0.
Would you agree to update your german translation?
That would be awesome !

**Comment by gedakc** [comment]
While we await updated translations I will manually test Manuskript functionality in an effort to minimize the chance of regressions slipping into the release.

**Comment by ScullyBlue** [comment]
Oh, yes, I would update the german translation. But befor next week I have not enough time. I hope its ok, if I give it later.

**Comment by olivierkes** [comment]
Entschuldigung @ScullyBlue , forgot to answer. Sure it's ok, send it when you have time :)
Thanks a lot !

**Pull request closed without merging**
