### PR TITLE
Chinese translation

### PR DESCRIPTION
**Pull request by lingsamuel**
Weblate is hard to use so I edit `.ts` file manually.

### CODE REVIEW

**Comment by gedakc** [comment]
@lingsamuel I noticed that these enhancements indicate updates to filenames with suffix `_zh` file and not `_zh_CN`.

Should these translations updates be placed into `i18n/manuskript_zh_CN.ts` and `i18n/manuskript_zh_CN.qm` instead?

**Comment by lingsamuel** [comment]
This branch base on old develop branch (which totally equals 0.8 master), so the translation filename is `zh`. I will change it to match new version.

**Comment by gedakc** [comment]
Would you be able to rebase this PR against the most recent **develop** branch?

Currently it contains conflicts and cannot be merged without manual intervention.

branch-conflicts

Thanks,
Curtis

**Comment by lingsamuel** [comment]
I executed `git rebase develop`, this may work.

**Comment by gedakc** [comment]
Thank you @lingsamuel for the updated Chinese (Simplified) translation.  With this PR I was able to successfully change the language to Chinese and it was displayed after I restarted Manuskript.

I have merged this enhancement with the **develop** branch for inclusion in the next release of Manuskript.

**Pull request merged**
