### PR TITLE
change markdown to "Markdown" in....

### PR DESCRIPTION
**Pull request by leela52452**
...A universal document converter. Can be used to convert markdown to a wide range of other formats.
see https://en.wikipedia.org/wiki/Markdown

### CODE REVIEW

**Comment by gedakc** [comment]
If the word "Markdown" is to be capitalized when referred to in English sentences, then have you checked for other usages of "markdown" that should also be capitalized?

**Comment by leela52452** [comment]
the  comment on weblate [source](https://hosted.weblate.org/projects/manuskript/translations/source/review/?type=sourcecomments) made sense to me and i proposed change. i haven't checked other instances. i will look into it after few weeks.

**Comment by gedakc** [comment]
> the comment on weblate [source](https://hosted.weblate.org/projects/manuskript/translations/source/review/?type=sourcecomments) made sense to me and i proposed change. i haven't checked other instances. i will look into it after few weeks.

Based on the _source_ link provided I think it was highlighting the whitespace in the string, not whether "Markdown" was capitalized or not.

**Comment by gedakc** [comment]
Since ["Markdown" seems to be referred to with a capital "M"](https://daringfireball.net/projects/markdown/), I will merge this PR with the **develop** branch.

**Pull request merged**
