### PR TITLE
Fix a number of typos in the code

### PR DESCRIPTION
**Pull request by sebras**
The last commit "Fix typo in pandoc file format" is perhaps controversial. I don't know the code well enough to determine if this will prevent Manuskript from loading already saved files. Perhaps it needs more work, but I need guidance in that case.

### CODE REVIEW

**Comment by sebras** [comment]
I noticed one of these while translating the software to Swedish, so I that prompted me to fix it.

**Comment by gedakc** [comment]
Thank you @sebras for your work to fix typos in the code.

I just had a *very quick* look.  Could you back out the "fix typo in pandoc file" commit?

The reason is because the word "Serie" is used in the stored file format.  If this word is changed then we must add another version to load_save.  Because this typo is not visible in the user interface I think we should hold off on fixing it until other improvements require an update to the file format.

**Comment by sebras** [comment]
Done. Though I think there is a high likelihood that the typo in the file format will remain forever.

I'm not sure if this is a typo which is Manuskript-specific or if it is related to pandoc itself, but I sense it is the former.

**Comment by gedakc** [comment]
@olivierkes will you have a chance to review this PR?

If not then I can take a more detailed look at it in the next few days.

**Comment by olivierkes** [comment]
Thank you very much @sebras! 

I'm very honored that you took the time to correct my terrible spelling. (I could be tempted to excuse myself saying English is not my first language, but I fear I would make as many mistakes in french ^^…)

Anyway I'll have to test it (in a few days). As @gedakc pointed out, we'll need to merge to develop, but that should not change much. And as for the typo in the file format, I could fix it with a hack so that it doesn't remain there forever. (But what is the typo again? Is it Series → Serie ?)

**Comment by gedakc** [comment]
> But what is the typo again? Is it Series → Serie ?

Currently "[Serie](https://github.com/olivierkes/manuskript/blob/d32ee37e84b4e7e3732f75eb36fbe52c77e8171a/manuskript/load_save/version_1.py#L134)" is used in the file format.  The correct spelling is "Series" (with the "s" at the end).

> ... as for the typo in the file format, I could fix it with a hack so that it doesn't remain there forever.

Adding a hack usually increases the complexity of the code unnecessarily.  My vote would be to:

- Either ignore the spelling mistake because it's only in the file format and likely only seen by programmers.
- Or fix the spelling mistake properly by adding another file format version.  This option does seem like overkill to me if done only for such a simple misspelling.

If we end up changing the format for characters (issue #252) then that might be a good time to slide in a correction for the file format spelling mistake "serie" -> "series".

**Comment by sebras** [comment]
> Adding a hack usually increases the complexity of the code unnecessarily

You could have the parser accept both "Serie" and "Series" but only write new files using "Series". That way it is fixed apart from old files until they are saved anew. Would that be suitable for you?

**Comment by sebras** [comment]
I did a new version rebased on the **develop** branch.

**Comment by gedakc** [comment]
> You could have the parser accept both "Serie" and "Series" but only write new files using "Series". That way it is fixed apart from old files until they are saved anew. Would that be suitable for you?

My preference is for no such hack to be added to the code.  Of course that is my opinion only.  @olivierkes has the final say as he created Manuskript.

**Comment by sebras** [comment]
> My preference is for no such hack to be added to the code.

I'm happy either way, I just wanted for you (both) to consider it. :)

**Comment by gedakc** [comment]
I just thought of another reason why I would prefer not to do the hack, and that is because it would break backward compatibility with older versions of Manuskript that recognize and load version 1 files.

Imagine the following scenario:

1. User A creates a project using 0.6.0 and passes it to a User B.  This fie is saved under file format **1**.

2. User B opens the project using upcoming 0.7.0 (which includes the hack), makes some updates, and passes it back to User A.  The file format is still saved as version **1**.

3. User A with 0.6.0 is now unable to open the project due to the file format "Serie" -> "Series" change.  The file format says it is version **1**, but in fact it is no longer the original version **1**.  In my opinion this breaks proper version control.

I still think that if we are going to fix this spelling mistake in the file format, then it must be made when a new file format version is created (e.g., **2**).

**Comment by sebras** [comment]
> this breaks proper version control

Ah, yes, I didn't think about sharing of documents.

> it must be made when a new file format version is created

Agreed, then it should probably happen along with fixing issue #252 as you mentioned before. :)

**Comment by olivierkes** [comment]
Good point @gedakc, I agree with that view. Hadn't thought about sharing documents either. 

So we leave it with the typo until next document format.

**Comment by gedakc** [comment]
Thank you @sebras for this patch set of spelling corrections.  I have reviewed the changes, tested the code and all appears to be well.  Hence I committed these changes to the **develop** branch.

One odd thing that occurred is that this PR did not automatically close.  I suspect that it is due either to being originally based on *olivierkes:master*, or because I rebased the change against the latest **develop** branch.  I tried editing the title properties to indicate the enhancements were for the **develop** branch but this does not seem to have had any effect.

Regardless the git repository looks okay and the two commits are now part of the **develop** branch.

**Comment by sebras** [comment]
> One odd thing that occurred is that this PR did not automatically close.

Ok, I might have done something silly. I know git quite well, but how github works is sometimes still a mystery to me...

> Regardless the git repository looks okay and the two commits are now part of the develop branch.

Excellent. I'm happy to hear that. Good luck with the next release! :)

**Pull request closed without merging**
