### PR TITLE
Added spanish translation (and changed "chuleta" for "guía rápida").

### PR DESCRIPTION
**Pull request by jmgaguilera**
I found this project some days ago (thanks to OMG Ubuntu). After testing a lot of software to write long documents I find this the best alternative to scrivener.

So I downloaded develop version. And added spanish translations to everything new. 

I changed "chuleta" for "guía rápida", I find "chuleta" has negative meaning (copy in an exam) and "guía rápida" is a better translation.

### CODE REVIEW

**Comment by olivierkes** [comment]
Thanks a lot !
I've seen that this pull request overwrites the french translation and leaves it empty (in `i18n/manuskript_fr.ts` everything is "unfinished").
Do you know how to avoid that?

**Comment by jmgaguilera** [comment]
Sorry, I didn't saw this problem. Now, I found that "manuskript_fr.ts" from your develop branch is committed with pending conflicts. I think that pylupdate5 doesn't find translation after first conflict.

I'll try to solve it. And I will send you a new pull request.

**Comment by jmgaguilera** [comment]
Just solved conflicts and added pending translations

**Comment by jmgaguilera** [comment]
Did you noticed I updated pull request to solve the problem with french translation?

**Comment by xisberto** [comment]
Is there any software I should use to contribute to the translations?

**Comment by jmgaguilera** [comment]
Look at this site: http://doc.qt.io/qt-5/qtlinguist-index.html There is a section named "Translators". It explains everything you need to know. You need the "linguist" (comman line name) tool from qt.

**Comment by olivierkes** [comment]
@jmgaguilera I'm really sorry, I did not notice you corrected it..
It's merged, many thanks !

**Pull request merged**
