### PR TITLE
Gtk Pull Request with way to many things (Again)

### PR DESCRIPTION
**Pull request by TheShadowOfHassen**
First here is everything that the old closed pull request says:

Sorry for the size. I made some of the changes with a downloaded zip file of the branch, and it just dawned on me that most pull requests are one thing at a time. Big omnibus pull requests won't happen again.

So I'm including a change-log, so you know everything I changed. Also, as a note you can probably tell anyway because I comment a lot. So You'll be able to tell if I looked at something because I comment on it.

So first it's probably pointless, but I changed the about screen to show the most recent version of Manuskript (0.14.0) changed the website to show the link. Personally I like to know what I'm clicking on, so I assumed others would, and finally I added a note that it's still in development. Just in case someone else stumbles upon it.

Second I remade the book of acts example because the other ran errors when I tried to open it.

Third I added a test.io in the main directory. It can be removed if you don't want it there, but I couldn't get it to run in its original place. Also, I added an Icon to the app.

Fourth because I wanted to get the hang of the manuskript port/libhandy I added what I've wanted for years. A template for the more info. It always sapped my writing speed having to keep over and over adding things for each character's hair and eye color and all the other stuff.

Next I fixed issue https://github.com/olivierkes/manuskript/issues/1107 at least temporary I know @TheJackiMonster and I were discussing different ways to do this but its easy enough to change back if needed.

Finally there is a tip of the day glade file and a blank box pane now in the overview glade file They can be deleted, but it's the start of another feature I want to add, but I wanted to discuss the feature before I implemented it. Yes I know that if I just implement 100 things I want in manuskript it'll still not work but I can't figure out custom drag and drop.

So there still is two more msk files there and if you don't want them I'll delete them next pull request(The only way I can think of doing it now is deleting this fork and starting all over again, but They were necessary for me because the original book of acts ran errors. I'll open an issue on why.

### CODE REVIEW

**Comment by TheJackiMonster** [comment]
Your commit still includes the sample project re-saved. Please remove that from the PR. You don't need to recreate the PR by the way. It's possible to just force push on the branch of your PR to replace the commits connected to it.

**Comment by TheShadowOfHassen** [comment]
I did it. Thank you so much for your patience. I am still very new using GitHub (and git) so I only barely know what I'm doing.

Let me know if anything else needs changed.

**Comment by TheJackiMonster** [comment]
Okay, so now there are still files with the `.glade~` extension. Those are temporary backup files from Glade and they should not be committed. Actually the `.gitignore` in the ui folder should already deal with that but it seems like you have added those files explicitly. Please remove them as well, so the PR only contains the edited files (I think that you be the last time to adjust anything in that regard ^^').

**Comment by TheShadowOfHassen** [comment]
There. That should do it. I deleted them. I have now clue how I didn't get rid of them before I didn't see them on github so I assumed they were gone. But apparently not.

**Comment by TheShadowOfHassen** [comment]
So was there anything else wrong?

**Comment by TheJackiMonster** [comment]
Haven't looked into the changes yet because I currently don't have much time until February. Only thing I can assume from the files so far that it's mostly UI without logic written in code. So I don't expect any bugs.

But that also means I can mostly comment on the UI visually regarding design when I check it. So I'm not sure whether you have started to write the logic behind those UI components already. But that might help for later testing regarding user experience, performance or data access. If there's only UI, the best I can do is assume the logic from own experience.

For now thanks for your efforts so far. I'll also try to make a release of the Qt code ready in February. Hopefully then there's some more time for me to work on the Gtk code again besides some other projects I have on my list. ^^'

**Comment by TheJackiMonster** [comment]
> All the features I added completely have their logic. if logic means the non UI part that works.

What I meant was python code... the files commited so far are only from Glade defining the UI. I hope this makes sense. If you have implemented the Python code/logic behind the UI parts, you can also commit them of course.

**Comment by TheJackiMonster** [comment]
> If you need help with parts of the Qt release I don't know Qt but I can help with testing or blog post writing. You'd have to open an issue or something to let me know. I want to help

Testing always helps if you open issues for the bugs or problems you notice. Usually before a release I try to go through a bunch of critical bugs and fix them. So every release brings a bit more reliability besides new features.

**Comment by TheShadowOfHassen** [comment]
Oops. Somehow my code didn't get uploaded. It's fixed through. All the logic is written and if you run it everything should work. 

After this pull request nothing silly like all of this will happen. I messed up this pull request but it should be fixed now.

**Comment by TheJackiMonster** [comment]
Okay, one thing I've noticed so far in the code: You seem to mix snake case and lower camel case for naming functions/methods. Please do only use lower camel case in the GTK port since I've started to use that consistently. Most important is that we don't mix naming conventions causing confusion.

Personally I don't have a preference but I think it is really useful to separate usage of the GTK API or Python standard library from the application's own code. So every function in snake case can be looked up while functions using lower camel case (or mixedCase) is from the application.

If we would write libraries I think we should use snake case because that is what the common [style guide](https://peps.python.org/pep-0008/) for Python suggests. But I don't think one or the other is more readable anyway. Just separating the origin should make it easier to contribute and find issues. For example we won't run into a problem that a function from application is called the same as in GTK or any other library as easily.

**Comment by TheJackiMonster** [comment]
Another thing we should try to do is starting all events/callbacks/handlers with an underscore. So those methods are private because it won't make sense to call them from another object/component anyway. Honestly I've produced most code which does not comply with that. So I will push some patches to the branch correcting that. ^^'

I assume I wanted to fix that before other people start contributing but here we are. Won't take long... ^^'

**Comment by TheJackiMonster** [comment]
Okay, I've looked at the code and the UI so far. I already corrected some parts. Multiple things I like to mention:
- Do not add comments to the code when it's not necessary! If you can read the code and immediately come to the same conclusion as reading the comment, it is redundant. Comments are only for complex code, especially in Python where most lines are extremely readable.
- Do not add empty lines if it doesn't segment your code into different sections. Many developers do not add empty lines at all if Python (or another language) doesn't require it. I personally add some to separate different sections of code in one function making it clear, they belong together. However IDEs like PyCharm will even underline your code in yellow or red if you add multiple empty lines in a row where they don't belong.
- Use an IDE with obnoxious highlighting of warnings and errors (I actually mean this - the more annoying the better). When there's any line marked red, orange or yellow indicating a warning, a spelling issue, a potential error... try to fix and avoid such cases. The main goal of the new GTK port is cleaning up the mess we had with Qt so far. Therefore any warning in the code should be addressed as it was an error.
- Something which accounts for UI and code: Do not just blindly copy & paste stuff! There are even multiple reasons why you should avoid doing it even if it looks as a convenient solution to some problem:
   - You don't learn anything by doing it. But software can only improve if the people developing it improve. So that doesn't help in the long run!
   - If there's code to use in multiple similar places... consider again if it's actually the *same* logic applying to both situations. If that truly is the case, abstract it into a function or class and reuse it, otherwise write an original solution for your individual problem.
   - Every time you copy & paste code, you will copy & paste the bugs inside that code. But now you have two places to fix them instead of one, multiplying amount the bugs...
   - In the case you still copy stuff to adjust small bits, make sure you understand it completely. Missing parts will break stuff!
- Another hint for coding and designing UI: Consistency is most important! This applies to naming conventions, syntax, design and even writing logic in functions. If your contributions look and feel as if they were part of the rest, I won't have any issues with it merging. The same applies to most (if not all) software projects by the way. First thing I do is always understanding how other people write and design it, before I contribute. So they need to refactor the least amount possible and we only need to discuss issues in details.

**Comment by TheJackiMonster** [comment]
Besides that I have some suggestions to the functionality. I think templates for character details are neat. But I think they should either automatically append/apply to new characters or we need some function to enable/select a template when creating a new character. Because we want to minimize interactions in UI to use it.

Another thing about the UI design is that we should avoid long labels/captions as much as possible. For example the text in the button from the characters tab under details info "Append Detail Template" makes the button extremely wide. However I think it's best to use space in UI in a ratio to how often users would look at them. Currently you would only use the button once for each character, I assume. But it's five times as wide as the button to add or remove another entry to the details info table.

So that is why I would suggest using a much shorter text or even better a fitting icon in the button. All buttons with icons should get tooltips at some point anyway. So if an icon is not 100% obvious to translate, the tooltip should cover this issue.

**Comment by jrstrick** [comment]
Wow. Programming may have changed a whole lot since I learned it, but the two suggestions about comments and whitespace would have gotten me Fs in my computer science classes. Code readability is *important*. Whitespace aids readability. Comments make algorythms clear for people who don't think exactly the same way you do, and they definitely make it easier to recover the mindset you had three years ago when you wrote this clever algorithm that no longer makes sense when you read it.
-JRS
Get BlueMail <https://bluemail.me> for Desktop
Tobias Frisch wrote:
Okay, I've looked at the code and the UI so far. I already corrected some parts. Multiple things I like to mention:
Do not add comments to the code when it's not necessary! If you can read the code and immediately come to the same conclusion as reading the comment, it is redundant. Comments are only for complex code, especially in Python where most lines are extremely readable.
Do not add empty lines if it doesn't segment your code into different sections. Many developers do not add empty lines at all if Python (or another language) doesn't require it. I personally add some to separate different sections of code in one function making it clear, they belong together. However IDEs like PyCharm will even underline your code in yellow or red if you add multiple empty lines in a row where they don't belong.
Use an IDE with obnoxious highlighting of warnings and errors (I actually mean this - the more annoying the better). When there's any line marked red, orange or yellow indicating a warning, a spelling issue, a potential error... try to fix and avoid such cases. The main goal of the new GTK port is cleaning up the mess we had with Qt so far. Therefore any warning in the code should be addressed as it was an error.
Something which accounts for UI and code: Do not just blindly copy & paste stuff! There are even multiple reasons why you should avoid doing it even if it looks as a convenient solution to some problem: 
You don't learn anything by doing it. But software can only improve if the people developing it improve. So that doesn't help in the long run!
If there's code to use in multiple similar places... consider again if it's actually the same logic applying to both situations. If that truly is the case, abstract it into a function or class and reuse it, otherwise write an original solution for your individual problem.
Every time you copy & paste code, you will copy & paste the bugs inside that code. But now you have two places to fix them instead of one, multiplying amount the bugs...
In the case you still copy stuff to adjust small bits, make sure you understand it completely. Missing parts will break stuff!
Another hint for coding and designing UI: Consistency is most important! This applies to naming conventions, syntax, design and even writing logic in functions. If your contributions look and feel as if they were part of the rest, I won't have any issues with it merging. The same applies to most (if not all) software projects by the way. First thing I do is always understanding how other people write and design it, before I contribute. So they need to refactor the least amount possible and we only need to discuss issues in details.

**Comment by TheJackiMonster** [comment]
> Comments make algorythms clear for people who don't think exactly the same way you do

As with everything in the world... it depends. Making redundant comments doesn't help anyone. For example:
```
# print a hello world message
print("Hello world")
```
Is a comment like this necessary? I don't think so. Will it make the algorithm clear? Not much more clear than the code itself. This even makes sense in more complex cases:
```
# load the content of all outline items in the project
for outlineItem in project.outline.all():
    outlineItem.load()
```
Like I mentioned Python is a very readable language. So writing comments being to close to the actual code will only create lines between the actual logic without more details. So developers start to ignore them all together.

Best documentation you can do is adding comments with explanations to functions/methods/classes describing what they are for. It also makes sense to add comments marking known issues, unexpected behavior or possible workarounds. So everyone coming by understands that it's not trivial to remove or replace those lines.

Similar goes for whitespace. Whitespace can be helpful as I mentioned but it can also be confusing (especially in Python when you don't have any brackets defining the body of a function or structure).

**Comment by TheShadowOfHassen** [comment]
I use thonny for an IDE. I am still a bit of a beginner. Any recommendations for Ubuntu that's not VS code would be great!

So are you making the changes and telling me to not do it in the mean time?

 I do probably over comment I'll cut that back and also make sure my segments do different parts of the code. I'll also match my forms to the others. That is just another habit but I can fix it. I don't want this to be like Qt. That code is a mess.

How about for commenting I just comment separating the parts of code. I.E  
`#Imports` or `#Now Gtk imports.` or `Now we add the {Insert something here I couldn't make something up}` and also explanation for complex parts.

I understood the copying and pasting and it worked but the advice is very sound in smart. I did learn a lot when I started by copying and messing with.

The choice of lowerCamelCaseLikeThis and not using underlines_like_this makes sense once you explain it. At first I was confused about that so I just followed the python style guide but I can change that in the future.

Also I can do the _ before functions....

Would it be Ok if I wrote all this up and put it in the branch during my next pull request? So I can have a sort of reminder when I program.

The template suggestions make sense. I had no idea. I can change it to an Icon and add a tooltip if you want or we could also add some sort of character set up wizard with templates. Your call.

I noticed you removed the scroll box from the tree editor in the template editor. Is there something else that allows scrolling? I'm curious because what if someone has 100 attributes or something.

Thank you so much for looking over it. Next week I'll have a lot of free programming time so if there are any changes you need me to do I can do it then.(I'm hoping we can get this merged then so I can work on the quote of the day)

If not and it looks like you've caught all the errors

**Comment by TheJackiMonster** [comment]
> I noticed you removed the scroll box from the tree editor in the template editor. Is there something else that allows scrolling? I'm curious because what if someone has 100 attributes or something.

Ah, I see. Then I removed too much. I just noticed that you copied the leaflet from another UI file which didn't had a purpose in this case. But the scrolling area would make sense, you are right.

About the commenting: It's not necessary to comment the imports in my opinion. It's best to sort the imports by packages anyway. So it can easily be obtained which functions and classes are used as well as from where. As stated before I personally think comments make the most sense when you have code which does not work properly yet or as originally planned. Because exceptions can not be trivially figured out by others without explanation.

About IDE: I currently use PyCharm which is freely available. I've also used VSCodium, QtCreator and Eclipse in the past. Obviously it depends on your preferences what to use. But I recommend using anything with a good level of validation and highlighting. If it doesn't you could also look for external tools and verify your code with that before submissions. Usually it is easier to include something like that in build/compile instructions but we don't really have that with Python...

**Comment by TheShadowOfHassen** [comment]
So I rewrote the template UI front end. It should look and work a a lot better. There is one problem. Somehow I cannot get Gtk.ModalButtons to click in the Gtk.ListBox so its Gtk.Buttons. I searched the internet but didn't find anything so it'll stay that way until I can figure it out.

Could you please check this out and tell me what else I need to change in order to get this to merge? It'll be easier if we don't have to keep fixing conflicts whenever the Gtk branch is updated. I also want to work on the quotes of the day.

P.S. Sorry about my spelling. I have a problem with it but its usually only when Mr. Spellcheck isn't there. I tried pycharm but when I set the interpreter to my Ubuntu local with all my libraries it ran errors. I started using builder which is sort of fitting seeing that I'm writing Gtk. It has spell check and I turned on code suggestions in Thonny when I use it.

**Comment by TheShadowOfHassen** [comment]
I found an actual python command to add to dictionaries together.

**Comment by TheJackiMonster** [comment]
Okay, I had the time to checkout your changes. Interesting idea to use those kind of menus. I assume if we want to use them, it would make sense to use them in other places as well. So the behavior is not confusing but expected to users.

It's definitely less hidden by design than context menus which some people actually missed in the past. Also I think it makes quite a lot of sense to have the templates available in the place where you need them instead of putting them in the main menu. So that's good.

The only thing which is missing, I think, would be a separate menu to delete templates. Maybe it might make sense to visualize the current content of a template as well. Because currently "appending" does override the content of a characters details. Also we probably want to prevent a user to accidentally append a template with many entries to then delete all rows manually. ^^'

It's definitely now harder to memorize what's stored in each template. What do you think?

**Comment by TheShadowOfHassen** [comment]
I was planning on when we do a entire undo/redo if you add/ overwrite you can just hit control z.

I added a delete menu.  There is a few TODO'S that I'll get to later once I make a new conformation Dialog. (In the next pull request with quote of the day) I do like the menu style and I think it would look good everywhere in manuskript.

 Memorizing templates shouldn't be a problem because If you just have one to apply to every human you're not going to need more than one unless you have aliens and then one for each different alien kind.

**Comment by TheJackiMonster** [comment]
> Memorizing templates shouldn't be a problem

I think you underestimate our users here. ^^'

For example I have a rather complex story with many different characters, be it humans, mutants, animals, mutated animals, cyborgs, demons, zombies and robots (roughly). If I now want to create a template for each category and remember what's included it's not trivial.

I think you are right that it shouldn't be a critical issue when used as types/categories of characters. But I would think seeing the content of a template which is stored, would still be useful. Especially considering that it doesn't store attribute names but also default values.

I assume we need to implement a global undo/redo at some point anyway but I'm honestly not sure how to do it yet. Because it needs to work with all data structures and all UI elements in all cases. So hacking it in manually into every new component will be awful to maintain and to test. Honestly I think implementing autosave and revisions first might be even less complicated because that will only jump from one state to another instead of reversing incremental changes.

**Comment by TheShadowOfHassen** [comment]
So I'm not 100 percent how we go about that... Maybe in another pull request we could set up some sort of ghost appearance if you single click and if you double click it applies. I'll look into it.


Undo/ redo will be pretty hard and I have no clue either, there is one thing that we'll need to get cleared up concerning git and data management. I'll open an issue about it.

**Comment by TheJackiMonster** [comment]
> So I'm not 100 percent how we go about that... Maybe in another pull request we could set up some sort of ghost appearance if you single click and if you double click it applies. I'll look into it.

I think if there was an option to visualize a template in a dialog as previously, this would solve my issue. Because then a user could always look into it before applying. But at the same time when you create multiple new characters with the same template, you don't have to open this dialog and save time.

You can probably event use the old code which allows editing the template because that would prevent a user from being forced to create a dummy character to edit templates and such things. It's likely the best of both worlds. You still have the quicker menu which is visually much more local to the actual UI view but still have the fine control.

Maybe it's even possible to remove the sub-menu step. So instead of navigating `Click to open menu` -> `Click append` -> `Click template`, just use `Click to open menu` -> `Click on template`. Then edit/replace/delete templates from a dialog. But I'm not sure since I've never really utilized those type of menus because they are somewhat hidden and resolution dependent. It's definitely possible to add more than just text as selection to it:
test-popover

What do you think? We could also use a HdyFlap for the list of templates to open via the button but it will be rendered above the table or sharing space with the table depending on window resolution. This would definitely allow enough space for buttons to add the meta-functionality besides applying a template but applying it could automatically close the flap as well acting very similar to GtkMenuButton with a GtkPopOver in the end.

**Comment by TheShadowOfHassen** [comment]
So I have an idea but I'm going to need a question answered. I can't find a lot of gtk information on the internet and the dev help written for C is 90% not useful.

So how to I apply one of the default color changing settings to a UI item in the code like 'destructive-action' ?

Thanks and I'll work on this too. Basically I'm thinking if when you single click an item it appears a preview on your editor and on a double click it applies. The seperate parts for deleting and editing was so you don't accidentally click the wrong button. I like it the way it is, but once we get feedback from testers I can understand why it could need to change.

I don't think the external editor is a good idea. If you need a different template you just create your first character of the species (or whatever) and then use that as a template.

**Comment by TheJackiMonster** [comment]
I don't think double-clicks should be used in most UI honestly. Because it's not intuitive at all. You need to explain a user some element utilizes double-clicks, otherwise they will never try using that or only accidentally. Because all elements theoretically could use that for some functionality but nothing practically does.

The only exception people assume a double-click does anything different at all is the desktop or file-browser to open or execute a file. But that has been learned for decades.

**Comment by TheShadowOfHassen** [comment]
Fair enough. I'll work on it. But please could we pull this request? You keep making changes and this keeps needing to have conflicts resolved
. I'll create a version  with a better template area. I was thinking either putting a little editing button so you can edit it or have a toggle button that makes a menu pop out of the side with a Gtk.Overlay and GtkRevealer with things you can right-click for deleting and editing. However I can't get as much work done if I need to keep resolving conflicts.

**Comment by TheShadowOfHassen** [comment]
I think that resolved it but, it'd be great if you could check.

**Comment by TheJackiMonster** [comment]
> You keep making changes and this keeps needing to have conflicts resolved.

You don't need to resolve anything. Just make another branch if you work on a different feature. I'll resolve any conflicts later on if necessary.

> I think that resolved it but, it'd be great if you could check.

You first merged but then reverted the merge. So that does not resolve the conflicts. Just leave it as is for now, if you're working on something else. Otherwise you could try to remove those two latest commits (merge and revert), so I can resolve the conflicts.

**Comment by TheShadowOfHassen** [comment]
So I don't know how to delete the commits sorry.

It'd be great if we can we can get this pull request merged. We can open an issue to discuss the template UI (Because the template UI would be very good if it was in a consistent location to other context suspfic actions. I.E. only for character or stuff.

**Comment by TheShadowOfHassen** [comment]
I simplified the UI.

**Comment by TheShadowOfHassen** [comment]
So I'd like to get this merged @TheJackiMonster could you check the UI and tell me what else need's changed?

**Comment by TheJackiMonster** [comment]
In current state I can't merge this PR because it reverts (e04b148c57b89f02a4a8045973a12c641678c514) changes I made on the upstream branch.

I'm not sure why you needed to revert things honestly. As a solution I would suggest you can go back to the commit when you added deleting templates ( 52c63a4763e02787f105395ab4de0684b9a906aa ), then you add the changes simplifying the UI ( c2828a03b99a505563180db28e698fcac37e5100 ) and I try to merge it afterwards.

I assume it should go similar to this:
```
git checkout 52c63a4763e02787f105395ab4de0684b9a906aa
git cherry-pick c2828a03b99a505563180db28e698fcac37e5100
git push -f
```

If the forced push doesn't work onto your branch, you can push the state to a different branch and open a new PR. But it should work theoretically. Maybe git just wants your branch to push on specified or something. The forced push replaces the history on your upstream branch with the one without the merge and revert. If you push on a new branch, you don't need the `-f` to force it of course.

**Comment by TheShadowOfHassen** [comment]
Did that fix it?

If not it might take me a few weeks to get around to reverting the commit because i don't have consistent internet.

**Comment by TheJackiMonster** [comment]
> Did that fix it?
> 
> If not it might take me a few weeks to get around to reverting the commit, but I'll do it.

No, as I said the problem is that you reverted changes from the upstream branch. Merging the newer state does not change that.

**Comment by TheShadowOfHassen** [comment]
Ok. I'll do it when I can.

You could look at my other PR, I don't think it's as nearly as messy.

**Comment by TheShadowOfHassen** [comment]
I fixed it. We can merge this

Oh, @TheJackiMonster  it'd require some redo of the UI, but it'd look even better if we could have a context menu pop out of the side, like.

image

It'd require a bit of changing, but we'd have to make the same changes to get an image in the background to work for a new full-screen theming, and it'd be easier to make the change now than later.

I made an issue #1119 with a question for you, but you never answered.

**Comment by TheJackiMonster** [comment]
> I fixed it. We can merge this

As I already mentioned. The commit history of this PR contains a revert of upstream changes. Merging a newer state of the upstream branch afterwards does not change that. That's not how git works. All conflicts previously "solved" by the revert won't get solved properly.

So no, I can't merge this for the same reason I mentioned already.

**Comment by TheShadowOfHassen** [comment]
I did what you said, what did I do wrong?

**Comment by TheJackiMonster** [comment]
> I did what you said

You did not. Either you didn't not force push to override the commit history or you did something completely different by merging upstream again and adding more changes. That's at least what the commit history tells me.

I mean, it's as I said. You either replace the commit history removing the revert commit (e04b148c57b89f02a4a8045973a12c641678c514) or you open a new branch from before and open a second PR with that. So I'll close this one here.

The alternative is that I cherry pick each and every one of your commits without the merges and the revert. But that will take time. To simplify things I already said it's best to not merge anything from your side. But either you still do for some reason or it's configured as automatic option in a tool you use for git. Not sure.

You should also be able to look into the commit history. As long as you see the revert commit, it's not fixed.

**Comment by TheShadowOfHassen** [comment]
I decided to make a new PR It's here: #1181

Does that one work?

**Comment by TheJackiMonster** [comment]
I think so. The revert commit seems gone. I'll close this one here then.

**Pull request closed without merging**
