### PR TITLE
Fixes: incorrect reference to 32px icon

### PR DESCRIPTION
**Pull request by gedakc**
This is a minor fix to ensure that the correct 32px Manuskript icon is referenced.

@olivierkes, I am working my way through learning QT, Model-View-Controller, and learning and improving Manuskript.  I am a big fan of your choice to use markdown text for storing the novel content.  I also like your choice of having the data stored in directories and plain text files which can be edited with other tools and still work with Manuskript.  Overall you've accomplished a lot with **Manuskript** to be proud of.  :-)

### CODE REVIEW

**Comment by olivierkes** [comment]
Thanks for your involvment !
As you can see from the code, I'm not a profesionnal programmer :) But i'm really glad you're helping now, it's encouraging.

**Comment by gedakc** [comment]
I am happy to help.  **Manuskript** is already a good tool, and I hope to work with you to make it even better.  :-)

Currently I have been focusing on improving stability and on getting core functionality to work.  I think it is important for us to get a new release out soon.  Especially with the problems creating and saving a new project with 0.3.0 (see issue #37).

Is there something specific you would me to work on to assist with a new release?

**Comment by olivierkes** [comment]
Yes you're right. I was hoping to close those issues before: https://github.com/olivierkes/manuskript/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.4.0
But the problems with 0.3.0 are serious enough to justify a new release, which I should have done a long time ago. I'll merge develop with master in the coming days.

Most important after that I guess would be packaging, either on Windows, OS X or Linux. Do you have any experience with packaging PyQt apps?

**Comment by gedakc** [comment]
I am new to Python and PyQt and have no experience with packaging these as apps.  I am willing to learn.

My core development computer runs Kubuntu 16.04, and I have many other virtual machines with such as Debian, Fedora, openSUSE, and Ubuntu.  I also have WinXP running in a VM if needed.  I do not have access to OS X.

Is there some specific packaging software you would like me to investigate?

**Comment by gedakc** [comment]
I am happy to read that you are on-board to create a new release. :+1: 

While I do not have experience packaging PyQt apps, I would be happy to test packages on various GNU/Linux distros as well as WinXP if needed.

**Comment by olivierkes** [comment]
For now I've been using a tool that freezes stuff in python, pyinstaller if I remember correctly, but I don't know if it's a good option. 

I know of some pyqt apps that are properly packaged, such as https://apps.ankiweb.net for example. But I don't know how. 

If you were willing to investigate that, it would really help expand the number of users!

**Comment by gedakc** [comment]
Per your suggestion I will investigate https://apps.ankiweb.net to see if I can learn how it is packaged so that we can be reproduce the steps with manuskript.

**Comment by gedakc** [comment]
To help our Windows users I have added a guide to [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows) while I investigate Python packaging.

**Comment by gedakc** [comment]
@olivierkes, on May 25th I sent you two email message.  The latter email contained a link to a Windows PyInstaller package for the 0.4.0 release that I created.

Did you receive the email?

**Pull request merged**
