### PR TITLE
Change words issue 181

### PR DESCRIPTION
**Pull request by gedakc**
This pull request includes enhancements to address issue #181 - Odd Word Choices in English - Take 2.

### CODE REVIEW

**Comment by gedakc** [comment]
Hi @olivierkes,

For your information, when I created this PR it looks like a number of processes were initiated on TravisCI/SemaphoreCI.

See above.

**Comment by olivierkes** [comment]
Thanks for doing this!
I might be wrong, but I think you missed one "Serie" in `manuskript/ui/mainWindow.ui` (there is 3 changes in mainWindow.py, but only two in mainWindow.ui).

(I don't know why Semaphore triggered stuff here. It's normal that it fails, because the test framework has not yet been pushed to master. In the future this will tell us for any PR if it passes the tests)

**Comment by gedakc** [comment]
> @olivierkes: I think you missed one "Serie" in manuskript/ui/mainWindow.ui (there is 3 changes in mainWindow.py, but only two in mainWindow.ui)

Thanks for catching this.  I'll take a look and re-push if/when I fix the issue.

**Comment by gedakc** [comment]
I had missed some of the "Serie" -> "Series" changes.

Note that I did not change the variable names.  I also did not change the entries in `manuskript/load_save/version_1.py` because these might adversely impact manuskript's compatibility with previous versions.  I wasn't sure so I left these alone.

**Comment by olivierkes** [comment]
Great! Haven't tested it, but looking through it it looks good. You're right, it's safer not to touch things `version_1.py`, or that would require more extensive testing.

(Do you have the right to merge a PR btw?)

**Comment by gedakc** [comment]
When I view the PR under the `olivierkes/manuskript` github repository, I can see a **Merge pull Request** button, so I assume I have permission.

Would you like me to merge the PR?

**Comment by olivierkes** [comment]
> Would you like me to merge the PR?

Yet do it, so that we know you can.

**Comment by gedakc** [comment]
I chose the **Rebase and merge** option in an effort to keep the git tree simple (less forks).  If you are not familair with `gitk`, install it and take a look at the output from `gitk --all`.

**Pull request merged**
