### PR TITLE
Logging and command-line arguments

### PR DESCRIPTION
**Pull request by worstje**
I originally intended to work on something else, but in the process of wanting to make that happen I needed to improve the logging and the way command-line arguments are handled. And by the time I completed those, I realized my original intention might be a bit more thorny than anticipated. But since these improvements are enough of a change to merit a PR, here it is.

At its core, these changes embrace the Python `logging` and `argparse` modules, and aim to improve life for maintainers, contributors and everyone inbetween.

## Features

- Manuskript now logs to a file in addition to the console.; Default location: `{datadir}/manuskript.log`
  - Due to spammy Qt considerations, the log is wiped every time Manuskript starts. *I reached a >1mb file during some of my initial testing runs where all I did was start manuskript.*

  - Using **-L** / **--logfile** switch allows one to override to a more convenient location.

- We now support different severity levels of logging.

  - Stderr receives severity + message for WARNING+.

    - Consequence: no more useless spam on console when all goes well! Huzzah!

    - More detailed logs on console can be enabled through the **-v** / **--verbose** flag.

      - 1x lowers to INFO level, 2x lowers to DEBUG level.

      - Does not affect log file contents.

  - Log file receives timestamp, category, severity and message for all log levels.

- Every log message has an associated category, making it easier to contextualize program flow.

- Qt messages are also redirected through the new logging system.

- Comprehensive logging of all software versions.

  - If run from a git repository, it also logs the revision

    - This is to minimize the back-and-forth while responding to issues. *'Are you on the latest commit of develop?'* is a common-enough question. This allows testers to use the exact version affected without having to ask. (Assuming a log file was posted...)

- Various small adjustments.
  - Most intend to make the logs more readable.
  - The model-refactoring one is because I got really confused due to code duplication, and it just happened to be in my tree still. It is a pretty simple improvement so I decided to just let it be.

### Argparse syntax

```
C:\Portable\Manuskript>py bin\manuskript -h
usage: manuskript [-h] [--console] [-v] [-L LOGFILE] [FILENAME]

Run the manuskript application.

positional arguments:
  FILENAME              the manuskript project (.msk) to open

optional arguments:
  -h, --help            show this help message and exit
  --console             open the IPython Jupyter QT Console as a debugging aid
  -v, --verbose         lower the threshold for messages logged to the
                        terminal
  -L LOGFILE, --logfile LOGFILE
                        override the default log file location
```

## Code considerations

All source files that do logging should have this at the top:
```
import logging
LOGGER = logging.getLogger(__name__)
```
*'Why `LOGGER` in uppercase?'* you might ask. Simply because I found myself writing or even auto-completing to `logging` instead of `logger` on several occasions.

Since the `logging` module has convenience functions to log to the root namespace, that means we silently lose the category for context and any special handling. Using uppercase LOGGER appears like a nice tradeoff: it should not be changed by any code and it stands out visually so that it is easy to spot any mistakes during code reviews. (Since I went through the trouble of implementing all of the logging system, I might as well take some effort to make it harder to use it wrongly in the future...)

## Your input is required

- This PR needs testing on:
  * Windows XP (I still haven't set up a good VM for it, sorry!)
  * Linux
  * Mac
- Please do not limit your testing of new functionality to a `git pull`.
  Assuming it works fine, **please prepare actual test packages / releases** and test that, too.
  *This is due to some path sniffing code to make the Github revision search work, as well as making sure the log file can feasibly be stored wherever it ends up being dumped in those situations.*
- Please post sample log files for every platform so I can make sure the output is as expected.

Admission: I haven't tested against old Qt versions quite yet, so please don't merge blindly. I have tried to take care to not shortcomings in old versions, but you never know.

## Not happy with something? Have a suggestion? Let me know!

It is a lot of new code, and I mostly went with what seemed intuitive to me. I submitted this PR relatively early so that any breaking changes won't ruin many hours of testing. 😄

### CODE REVIEW

**Comment by gedakc** [comment]
Dealing with the excessive amount of logging to the terminal is something we would have to deal with eventually.  Kudos to you for tacking this task.

I've only had a cursory look at the code and agree that we don't want to rush merging this commit.  It touches many areas and thus can affect much of the functionality in Manuskript.

My first roadbump occurred when I started Manuskript on Kubuntu 16.04 and clicked the **Open** button to try to open a project.  Console log follows:

```
$ bin/manuskript 
Traceback (most recent call last):
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/ui/welcome.py", line 152, in openFile
    lastDirectory = self.getLastAccessedDirectory()
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/ui/welcome.py", line 60, in getLastAccessedDirectory
    LOGGER.info("Last accessed directory \"{}\" loaded.".format(lastDirectory))
NameError: name 'LOGGER' is not defined
gedakc@kaby:~/workspace/manuskript.gedakc$ bin/manuskript 
Traceback (most recent call last):
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/ui/welcome.py", line 152, in openFile
    lastDirectory = self.getLastAccessedDirectory()
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/ui/welcome.py", line 60, in getLastAccessedDirectory
    LOGGER.info("Last accessed directory \"{}\" loaded.".format(lastDirectory))
NameError: name 'LOGGER' is not defined
```

Regarding testing with older versions of Windows, you might wish to look at the following article on [How to Get a Windows XP Download Free From Microsoft, Legally](https://www.makeuseof.com/tag/download-windows-xp-for-free-and-legally-straight-from-microsoft-si/).  Note that I haven't tried out the steps in the article.

**Comment by worstje** [comment]
Eh... that is just me being an utterly neglectful idiot. I forgot to put the lines preparing the file-specific logger at the top of the file. After going through so many files (I just made sure with a quick grep on the entire branch), you sniffed out the one case where I screwed up! 😄

**Comment by gedakc** [comment]
I created a win32 package (`manuskript-0.10.0-with-PR667-logging-c36c30bc.zip`) of this PR and uploaded it to [Manuskript Testing Directory](https://sourceforge.net/projects/manuskript/files/manuskript/testing-only/) for your testing consideration while I am in the midst of home renos.

**Comment by worstje** [comment]
That is greatly appreciated; I just haven't found the time to follow the instructions you linked since I suckered myself into write a short story. 😅 But it also happens to be serving as a little testbed for the changes in this PR, so I'll definitely try using your test release and see how far I can get with that later tonight.

Good luck on your home renovations; there's no rush over here so take your time! 👍

**Comment by worstje** [comment]
Other than the already fixed snafu above, I spotted a tiny little aberration in the logfile when running the test version you prepared:

    2019-10-23 06:00:23,025 - manuskript - INFO - * Markdown <module 'markdown.__version__' (<pyimod03_importers.FrozenImporter object at 0x0277DFD0>)>

I am not sure why it struggles obtaining the version for that module. Clearly it is something related to PyInstaller; the rest of the entries show no problems.

I'll look into it one of these days but right now it looks like some accidentally exposed PyInstaller guts that I encroached upon. Since there aren't that many prepared builds to begin with, I don't consider this a show-stopper right now; no errors are thrown, it is just a slightly-less-useful logfile.

(I am aware that the recently released Python 3.8 has a builtin module to handle much of the version inquiry stuff, but we won't be able to rely on that for quite some time.)

I might add another line of version info that contains PyInstaller-related metadata when I have some time. At one point I have come across code that tested for the presence of PyInstaller, so I know that is possible. Beyond that there might be some other useful PyInstaller tidbits that are worth having in a logfile, but I'll have to dig into PyInstaller to master all that.

The PR and that build in particular still need more testing (there's no way a few hours of writing on my part covers all the buggy potential), but for now it seems we have dodged the curse of the old Qt version wrecking the party. 🎉

**Comment by worstje** [comment]
@gedakc I have spent the past two hours on getting a working WXP test & build environment, but I can't seem to get it to work right... thus this comment to ask for advice.

First, I have utilized [Running From Source](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows) to get the basics working, and that works.

But then the PyInstaller bit comes to give me a headache. I manage to build it using the instructions.

I have utilized both [this set of instructions](https://github.com/olivierkes/manuskript/wiki/%5BPackaging%5D-Generate-Windows-binaries-with-pyInstaller-(HowTo)) and [this other set of instructions](https://github.com/olivierkes/manuskript/wiki/Package-Manuskript-for-Windows-with-PyInstaller).

Everything appears to have packaged up (a bunch of warnings but that is par for the course according to the internet), but once I run the packaged end result I end up with this:

```
C:\manuskript\dist\manuskript>manuskript.exe
Traceback (most recent call last):
  File "C:\manuskript\bin\manuskript", line 11, in <module>
    from manuskript import main
  File "c:\python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "C:\manuskript\manuskript\main.py", line 8, in <module>
    import manuskript.ui.views.webView
  File "c:\python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "C:\manuskript\manuskript\ui\views\webView.py", line 34, in <module>
    from PyQt5.QtWidgets import QTextEdit
ImportError: No module named 'sip'
[1772] Failed to execute script manuskript
```

The log file created during the build never even mentions the sip module.

I have tried a couple of things - reinstalling PyQt5, checking if there is a pip version of PyQt5 5.5.1 I can use instead (no) - and some command line switches for PyInstaller ('--hidden-import sip' and even PyQt5.sip), but it doesn't produce any better results.

The closest warnings I come across are:

```
missing module named 'PyQt5.QtWebEngineWidgets' - imported by manuskript.ui.views.webView (conditional, optional)
```

But that is part of a different import a few lines (QtWebEngineWidgets, not QTextEdit) so that still doesn't explain why it isn't bundling the sip properly.

One thing I have not tried (because the PyQt5 installer should install it on itself) is to try and install a version of sip through pip as well. If they were necessary, I reckon it would be in the instructions.

When you have some free time (no rush!), could you check on your end to see how your build environment differs from the suggested downloads / versions in the wiki?

**Comment by worstje** [comment]
I just spotted the recent bouts of activity regarding the 0.11.0 release which reminded me this PR existed. (Unfortunately life has kept be busy so all my plans to implement some improvements kind of went up in smoke.)

This PR has been rebased on current develop branch to solve the conflicts with commit 9f6b65a.

@gedakc Is there anything about this PR that needs to happen in order to include it in 0.11.0?

Note that I have been using this branch as my sole driver ever since my last update and have had no further issues with the functionality itself. Perhaps we need some (wiki) documentation regarding the new log file this implements and bug reports, but that's IMHO something to tackle for the 0.11.0 release after this makes it into develop to begin with.

(The packaging issues from my last post of being unable to reproduce your test build were never completely figured out, but that seems to come down to differences in the version used for packaging that I was unable to narrow down further despite trying a few different PyInstaller releases. It is probably worth it to document the versions and other details necessary for a reproducible build at some point.)

**Comment by gedakc** [comment]
It's good to hear from you @worstje.  I've also been too busy to spend much time on the project and this will continue into February for me.  As such I won't be able to adequately review and test this PR for inclusion in 0.11.0.

The reason I want to get 0.11.0 out soon is because it addresses a critical bug that can result in loss of data when a person copies and pastes into the **Notes / References** and **Summary** sections.  If this release is done soon, then there is a better chance that it will make it into the next Ubuntu 20.04 Long Term Support release which has support for the next 5 years.

Curtis

**Comment by worstje** [comment]
Frankly, if 0.11.0 is going to end up in a LTS release of a major distribution, then I definitely want to see this included. The sooner we can step away from users copy-pasting log files from terminals and just upload a log file, the simpler bug reporting becomes.

If every support request starts out with having to figure out what steps people need to take to offer us useful debugging information (which might include copying from terminal, which can be rather awkward depending on the device used!), I'd consider it a barrier to effective troubleshooting, not to mention the extra drain on limited time resources of those who try to help out with bug reports.

Note that submitting a log file will cut out the existing dance of 'what version of Qt are you using', 'look in the About window for versions', etc. that are common counter-questions on newly opened issues right now.

**Comment by gedakc** [comment]
Your preference is noted.  Unfortunately I just do not have the free time to adequately review this PR.

**Comment by worstje** [comment]
@TheJackiMonster : I read in one of the other issues that you are looking for status updates on outstanding issues and PRs. Hence the mention. 😄 

This PR is quite ancient at this point, but it has been the only manuskript version I've used in the past year. For as far my experience on Windows goes, it is reliable to the level where I haven't had any crashes. (Or at least not any that involve this PR!)

But at this point, it is outdated. It will need merging / rebasing. While doing so, all new code should be vetted against `print` calls in case other PRs have since added new output that should be integrated into the logging system.

Additionally, it still needs testing on Mac/Linux.

**Comment by TheJackiMonster** [comment]
Unfortunately I can only test it on Linux but I would assume it that shouldn't be a huge problem.
> But at this point, it is outdated. It will need merging / rebasing. While doing so, all new code should be vetted against print calls in case other PRs have since added new output that should be integrated into the logging system.
It would be great if you could do that. The commits should also be squashed before merging. If there will still be some missed print() statements to replace, I can also do that after merge.

**Comment by worstje** [comment]
I'll try to do so this weekend. I'm not sure if I'd want to squash _all_ of the commits though; IIRC there's a bit too much varying functionality that is just logically separate enough to squash everything into a single commit. The commit messages have a fair bit of background on design decisions taken and tests done, and I feel squashing too much might actually be detrimental down the road. All the library versions we 'support' make for a very treacherous minefield.

I'll see what I can sensibly squash it down to.

**Comment by TheJackiMonster** [comment]
I have encountered a crash during launch in line 292 of logging.py:
> enchant_lib_ver = enchant_lib_ver().decode('utf-8')

It says: _AttributeError: 'str' object has no attribute 'decode'_

Maybe this is something which is caused by using a newer version of Python or you didn't test with enchant installed. So this has to be fixed.

**Comment by worstje** [comment]
Ah, it is probably a mix of the two!

I couldn't run enchant from source on my win64 python install because there was (is?) no wheel for it. So my daily driver runs with one of the other spellcheck modules.

The fact the code is there though shows I did test to some degree, but I have no memory of the environment that code used to be running in.

...

Further investigation turns up [some new releases(!!!)](https://github.com/pyenchant/pyenchant/releases), of which [release v3.1.0](https://github.com/pyenchant/pyenchant/releases/tag/v3.1.0) explicitly calls out changing the type for the variable in question from a `byte` to a `str`. A simply `isinstance` call will sort that out.

So thankfully not an oversight back then; just a library that has finally been resurrected to make more sense! 😄

**Comment by TheJackiMonster** [comment]
@worstje Do you think you can get this pull request updated to the current state of Manuskript? Otherwise I would uncheck it from the next release milestone again. So it could still come later...

**Comment by worstje** [comment]
@TheJackiMonster Sorry it took me a while; between being busy IRL, forgetting until your bump and literally everything else getting in the way of actually getting to the meat of this PR since then, I've kind of let you hanging.

Anyway, the PR is fully rebased. The previously mentioned issues have been taken care of, which includes all the remaining `print` statements. Some remain, but those were either commented out, part of a debug function in the middle of a markdown parser that didn't need more overhead, or a general purpose function `printObjects` that is only ever called by the test suite. Whatever the deal is with these instances, I didn't think resolving their existence was something to take care of in this PR.

One POSIX thing that does need testing that I can't on Windows are the signal handlers. I added an extra log message there, but I don't have a single clue how well Python has managed to hide away the specialness of signals. (I know that in pure machine code, they are a segfault waiting to happen.) Since it is Python, I assume they've been made to behave, but I'd be amiss to not mention that tiny addition there.

Thanks for your patience!

**Comment by TheJackiMonster** [comment]
Ok, I think it's looking good for getting merged. I can probably look through the source code in the future changing other print() statements as well. But the PR will already make error reporting much easier, I assume.

Also I have tested running it on Arch Linux now. I have also tried using SIGINT to cancel during startup. It seems to get recogniced to quit the program properly. So I don't think there's a problem regarding POSIX. It even saved my files before quitting. This is really good.

I will try to figure out how to get all release binaries build in the next weeks then. ^^'

**Pull request merged**
