### PR TITLE
Minor grammar fixes

### PR DESCRIPTION
**Pull request by RiderExMachina**
Fix grammar regarding multiple of an object.

### CODE REVIEW

**Comment by gedakc** [comment]
Thank you @RiderExMachina for this patch.

All new manuskript development is performed on the **develop** branch in the git repository.  As such would you be able to rebase the Pull Request on the **develop** branch?

As indicated this is a minor wording patch.  In a strictly correct world we would handle grammar singular and plural forms based on the number.  For example: "_1 Chapter_" and "_3 Chapters_".  However I think involves more complexity than is really necessary.

@olivierkes,

Currently the base language translation files are out-of-date on [Weblate - Manuskript Translations](https://hosted.weblate.org/projects/manuskript/translations/).

Would you be able to update these?

Longer term it would be beneficial if I could update the base language translation files on weblate as well.

Thanks,
Curtis

**Comment by RiderExMachina** [comment]
@gedakc Yes, I can move this to the **develop** branch. I had the same thought process about singular vs. plural usage and felt that the plural form would be used more often. I can toy with creating an adaptive version, but I fear that may be more trouble than it's worth

**Comment by gedakc** [comment]
Thank you @RiderExMachina for this grammar improvement patch.

In order to incorporate this PR without a separate merge commit I used the `git cherry-pick` command.

The commit can be viewed at [Minor grammar fixes](https://github.com/olivierkes/manuskript/commit/2fdf8c64bf00f9f2913922f9c574436b20157848)

Closing this PR as merged.  :-)

**Comment by RiderExMachina** [comment]
Thanks for your help, @gedakc!

**Comment by gedakc** [comment]
This commit has been reverted so I am marking it as **invalid** so that it does not get picked up by the automatic generation of CHANGELOG.md.

**Pull request closed without merging**
