### PR TITLE
- adding characters count. Implementing #334

### PR DESCRIPTION
**Pull request by lechbaczynski**
@gedakc , you made me do rebase interactive, cherry pick and squash ;-)

### CODE REVIEW

**Comment by gedakc** [comment]
With manuskript we try to support screen sizes as small as 1024x600 pixels that are popular with netbooks (small laptops).

manuskript-char-count-obscure-word-count

With this patch applied I observed two issues:

1.  The format of the character count number does not match the format used for other values, such as word count and word goal.
2. The display of the character count causes the word count to be partially hidden, and the word goal to disappear.

The first issue should be easy to fix, but the second issue is not as easy due to the reduced screen area available on small laptops.

My thoughts are that if a writer is trying to attain a specific goal for the amount of written material, this is either specified in a word count, or in a character count.

If this is the case then to work around this issue perhaps we should have a setting that can toggle the display to either words (default) or chars.

What are your thoughts?

**Comment by gedakc** [comment]
Your view on the GUI changes required to support goals in either words or chars as defined by a program setting seem correct to me.

A different approach might be to only display the chars count if there is sufficient screen space to display the chars couny in addition to the word count and word goal.  This would likely be a smaller change to the code base and would perhaps still meet your need for a chars count.

The reason for suggesting only displaying the chars count if and only if there is room is because Manuskript was designed to help support large written projects such as novels with many plots and characters.  For such projects the word count is of higher importance.

**Comment by lechbaczynski** [comment]
'A different approach might be to only display the chars count if there is sufficient screen space to display"

This might lead to users' confusion, like" where is characters count?  Why cant't I see that? Why my colleague sees car count and I do not? Is there a switch in settings?

But it may also be like that noone will care about that :)

I could try to make it so, if I'll be able to find editor window's size and calculate char and word count + progress bar size (in pixels?) - this might be tricky.

**Comment by gedakc** [comment]
Designing a User Interface is not an easy task.  When making decisions it helps if the project has clear focus backed up by a mission statement.  That way requests can be reviewed in light of the main purpose for the application and decisions made accordingly.  With that said I have not seen a mission statement.  Perhaps that is one more thing that needs to be done to help improve manuskript.

I think that adding a character count has value to manuskript users.  My concern arises when the character count takes precedence over the word count.   This is because I believe the purpose of manuskript is to help create large written works where a text editor or word processor lacks features to help with organizating such endeavours.

**Comment by TheJackiMonster** [comment]
I have merged these changes from this PR to my fork and added settings to it, so the folders and texts in the tree-view can also show the amount of chars instead of words if selected. The amount of chars will only be shown (like in the upper screenshot with the problematic format at the moment) if it's activated in general settings.
But this was more an experiment than a solution.. ^^'
I will try to work on a proper solution which considers all the mentioned points here. Shall I open a new request when I'm done or can I adapt this one somehow? (I would guess not but it would be my second PR, so I really don't know. ^^)

**Comment by TheJackiMonster** [comment]
Okay, I think I have something which should work... the default settings will disable the rendered char-counter next to the word-counter but it will enable a tooltip. So you can hover over the word-counter to see the amount of chars and it's still allowed to activate it for people with enough screen space.
image

**Pull request merged**
