### PR TITLE
prevents crash when creating a project before selecting a model

### PR DESCRIPTION
**Pull request by c-cesar**

### CODE REVIEW

**Comment by c-cesar** [comment]
There is any problem with the PR?

**Comment by Loogix** [comment]
I also faced this issue. A simple click on the template do not select it, and this was quite frustrating. I hope this PR will be merged soon.

**Comment by gedakc** [comment]
@c-cesar it is good to see others, like yourself, helping to improve manuskript.  :-)

I am new to github development, but a longtime SourceForge developer. From what I can see with @olivierkes manuskript repository, development is performed on the git **develop** branch. Hence the most up-to-date code can be found in the **develop** branch. To me this indicates that patches or pull requests should be based on the **develop** branch, and not based on the **master** branch. If anyone knows differently then please feel free to correct me.

From looking at your pull request, it appears that at least a portion of the changes were already implemented on the **develop** branch under issue #44.

@c-cesar perhaps you might try the @olivierkes **develop** branch, and if required base your enhancements on the **develop** branch?

**Comment by olivierkes** [comment]
Thanks @c-cesar ! I'm sorry I failed to see those pull request (as you can probably see in the code itself, I'm a self-taught coder and still learning much).

As @gedakc said, this was fixed in #44 in the develop branch.

**Pull request closed without merging**
