### PR TITLE
- updates the spanish translation -

### PR DESCRIPTION
**Pull request by alpezmar**
I've updated the Spanish (Español) translation of the project. Everything should be fine (I've tested it, nothing crashed and looked fine), however I'll still look for inconsistencies, as the previous translator maybe used slightly different terms for some words.

I only have one doubt. When doing the translation some terms had a "&" character in them. I looked and it made the word had a little _ under the following letter. I supposed it was for keyboard shortcuts. I tried to keep the "&" next to the same letter but that wasn't always possible. Should I leave the "&" where it is or maybe should I put the corresponding letter between parenthesis (e.g., "Eliminar (&d)" instead of "&Delete")?

### CODE REVIEW

**Comment by gedakc** [comment]
Thank you @alpezmar for the updated translation.

The "&" are used as you thought -- these are used for keyboard shortcuts.  It would be great if the shortcut letters remained the same across all translations, but I recognize that this will not always be possible.  Hence you may need to make decisions on what to do in these situations.

When submitting PRs please base these on the **develop** branch.  Hence please either rebase this PR on the **develop** branch, or if not possible then make sure to base against the **develop** branch when you create a new PR.

Curtis

**Comment by alpezmar** [comment]
Ok, @gedakc, I've changed the base to the developer branch. Sorry, I'm still not too familiar with the git process. I will then fix the issue with the shortcut labels and submit the changes, as well as other format fixes.

I'm glad to contribute to the project!

**Comment by gedakc** [comment]
No worries.  :-)  Different projects use git branches in different ways.

I added a note to the main page that all PRs should be based on the **develop** branch.

**Comment by gedakc** [comment]
Thanks @alpezmar for the updated translation.

@olivierkes,

Would you be able to review this PR and either commit or advise if any changes are required?

Thanks,
Curtis

**Comment by gedakc** [comment]
@alpezmar, I have committed the Spanish translation from [hosted.weblate.org](https://hosted.weblate.org/projects/manuskript/translations/) into the git repository **develop** branch.  

Would you be able to test to see if works on your computer?

**Comment by gedakc** [comment]
I have pulled the translation updates from [weblate](https://hosted.weblate.org/projects/manuskript/translations/) and pushed these to the **develop** branch.

**Pull request closed without merging**
