### PR TITLE
Reworking of the translation loading process (issue #619)

### PR DESCRIPTION
**Pull request by worstje**
Two patches for the price of one. 😄 

The first is a bugfix for issue #619. I never had the original issue, so I cannot confirm it fixed... but it definitely should be.

The second is an improvement in functionality to more accurately determine the language to show a user by basing the language to show off of the preferred UI language as opposed to the system locale.

Additionally, this adjusts the messages emitted to the console to make it more clear what is happening. (The old messages just confused me too much while I was working on the code, sorry!)

I have tested this PR on Windows 10, but Mac and Linux probably need some love still.

For the auto-detection, I did this by removing the 'applicationTranslation' setting manually in the registry (the Manuskript UI only lets you set it to an empty string, which corresponds to the builtin 'US English' selection. I did not feel it necessary to add something UI-side to reflect this settings 'null state' since any normal user would just select the language they need and be done with it. 😁

### CODE REVIEW

**Comment by gedakc** [comment]
This PR looks good to me and worked when I tried changing the language from the default (English) to another language (Deutsch) and also back to the default.  Note that Manuskript must be restarted between each language change.

With my native language being English I have not fully tested the problem as described in issue #619.  To do so requires the default language to be non-English.

If no concerns are raised then I plan to merge this PR with the **develop** branch in the next day or so.

**Comment by gedakc** [comment]
Today I created a LinuxMint 19.2 Cinnamon desktop VM with French (fr_FR.UTF-8) as the default locale.

Test results for this PR:

- On first startup the default locale of French is loaded and used in the Manuskript GUI.
```
$ ./bin/manuskript 
Debug: Web rendering engine used: QWebView
qt5ct: using qt5ct plugin
Running manuskript version 0.9.0.
Preferred translation: ['fr-CA', 'fr'] (based on available ui languages)
Loaded translation: manuskript_fr_CA.qm
qt5ct: D-Bus global menu: no
Loading: /home/user/test-doc.msk
Detected file format version: 1. Zip: True.
Le projet /home/user/test-doc.msk a été chargé.
Le projet test-doc.msk a été enregistré.
```

- Changed language setting from "English" to "French", restarted manuskript, and was presented with French translation.
```
$ ./bin/manuskript 
Debug: Web rendering engine used: QWebView
qt5ct: using qt5ct plugin
Running manuskript version 0.9.0.
Preferred translation: manuskript_fr.qm (based on user setting)
Loaded translation: manuskript_fr.qm
qt5ct: D-Bus global menu: no
Loading: /home/user/test-doc.msk
Detected file format version: 1. Zip: True.
Le projet /home/user/test-doc.msk a été chargé.
Le projet test-doc.msk a été enregistré.
```

- Changed language setting back to "English", restarted manuskript, and was presented with the builtin English language.
```
$ ./bin/manuskript 
Debug: Web rendering engine used: QWebView
qt5ct: using qt5ct plugin
Running manuskript version 0.9.0.
Preferred translation: builtin (based on user setting)
Using the builtin translation.
qt5ct: D-Bus global menu: no
Loading: /home/user/test-doc.msk
Detected file format version: 1. Zip: True.
Project /home/user/test-doc.msk loaded.
Project test-doc.msk saved.
```

Hence with this PR code change, for a non-English default locale to use English one must first change the Manuskript setting to something other than English, then back to English, then restart Manuskript for the builtin English to be chosen.

While this might not be optimal, it does provide a way for non-English default locales to select the builtin English language.  Additionally no change to the file format is required for this functionality to work.

If no concerns are raised then I plan to merge this PR with the **develop** branch in the next day or so.

**Comment by gedakc** [comment]
Thanks @worstje for this functionality improvement.  I will merge this PR with the **develop** branch for inclusion with the next release of Manuskript.

**Comment by dyuan42** [comment]
Any way to fix this on mac? Preferably with a screenshots guide since I can't read anything in Japanese which is what the program is set to

**Comment by TheJackiMonster** [comment]
> Any way to fix this on mac? Preferably with a screenshots guide since I can't read anything in Japanese which is what the program is set to

Unsure where the configuration of Manuskript is stored. On Linux it's stored under `~/.config/manuskript/manuskript.conf`. So if you would delete the configuration file, it should reset back to English as default on startup.

**Pull request merged**
