### PR TITLE
Friendly logging for end users

### PR DESCRIPTION
**Pull request by worstje**
I ended up doing a bit about improving logging friendliness than was discussed in issue #852.

**This PR implements the following features:**

✔️ It now logs to a file in $datadir/logs/ of which the format includes a timestamp and process id.
✔️ The -L argument switch also benefits from this; it is now processed by a slightly improved `strftime()`, with the added placeholder *%#* which inserts the process id.
✔️ The Help menu now has a menu item that leads to a new (and currently very-dummy) page that should come to serve as a landing page for people seeking help.
✔️ The Help menu also contains a menu item to help locate the current log file. The easier we make it to submit logs, the better.

**Things I have _not_ tested:**

❔ All lines should be translateable, but I honestly have no clue how the translation system of Qt works exactly.
❔ I am not sure how well the 'Locate log file' function works on Mac and Linux as I have no way to test those for myself.

### CODE REVIEW

**Comment by TheJackiMonster** [comment]
I don't think the logs have to be translatable... or at least they should not be translated. Otherwise it's way more difficult for developers to read a users logfile, finding an error or fixing a bug. ^^'

**Comment by TheJackiMonster** [comment]
By the way on Linux with Gnome and Nautilus the fallback for opening the file explorer works fine.

**Comment by worstje** [comment]
> I don't think the logs have to be translatable... or at least they should not be translated. Otherwise it's way more difficult for developers to read a users logfile, finding an error or fixing a bug. ^^'

The translatability is not in regards to the logs themselves, but in regards to the menu items and associated dialogs which offer the extra information to be concerned about.

**Comment by TheJackiMonster** [comment]
I see... then it shouldn't be a problem. Qt usually scans the .ui- or its generated .py-files for strings to generate the translation dictionaries which can be filled for different languages. So as developer there is not much effort to do.

**Comment by worstje** [comment]
As long as it checks the not-autogenerated `manuskript/mainWindow.py` in this commit (which is not to be confused with its twin in `manuskript/ui`!) , because that's where the simple `QMessageBox`es with some new translatable strings is hiding. :-)

**Comment by TheJackiMonster** [comment]
Translation should not be an issue. I have tested and created a translation from English to German with Qt Linguist. So this should work fine.

**Comment by TheJackiMonster** [comment]
I think I still gonna merge this pre-release. It adds some parts into GUI which need extra translation but I'm unsure if people have started going through that process already. In worst case I will need to merge translation files which should be fine... I assume. ^^'

**Pull request merged**
